import { request } from '../utils/request.uts'

/**
 * 上传群文件
 */
export function uploadGroupFile(groupId: number, filePath: string) {
  return request({
    url: '/system/im/group/file/upload',
    method: 'POST',
    formData: {
      groupId: groupId,
      file: filePath
    }
  })
}

/**
 * 获取群文件列表
 */
export function getGroupFileList(params: any) {
  const groupId = params.groupId || ''
  const pageNo = params.pageNo || 1
  const pageSize = params.pageSize || 20
  const fileName = params.fileName || ''
  const fileType = params.fileType || ''
  
  let url = `/system/im/group/file/list?groupId=${groupId}&pageNo=${pageNo}&pageSize=${pageSize}`
  if (fileName) {
    url += `&fileName=${fileName}`
  }
  if (fileType) {
    url += `&fileType=${fileType}`
  }
  
  return request({
    url: url,
    method: 'GET'
  })
}

/**
 * 删除群文件
 */
export function deleteGroupFile(id: number) {
  return request({
    url: `/system/im/group/file/delete?id=${id}`,
    method: 'DELETE'
  })
}

/**
 * 记录文件下载
 */
export function downloadGroupFile(id: number) {
  return request({
    url: `/system/im/group/file/download?id=${id}`,
    method: 'POST'
  })
}
