package com.shengyu.module.system.dal.mysql.im;

import com.shengyu.framework.common.pojo.PageResult;
import com.shengyu.framework.mybatis.core.mapper.BaseMapperX;
import com.shengyu.framework.mybatis.core.query.LambdaQueryWrapperX;
import com.shengyu.module.system.dal.dataobject.im.ImChatMessageDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface ImChatMessageMapper extends BaseMapperX<ImChatMessageDO> {

    default PageResult<ImChatMessageDO> selectPageByChatId(Long chatId, com.shengyu.framework.common.pojo.PageParam pageParam) {
        return selectPage(pageParam, new LambdaQueryWrapperX<ImChatMessageDO>()
                .eq(ImChatMessageDO::getChatId, chatId)
                .orderByDesc(ImChatMessageDO::getId));
    }

    @Update({"<script>",
            "UPDATE im_chat_message",
            "SET status = #{status}",
            "WHERE id IN",
            "<foreach collection='ids' item='id' open='(' separator=',' close=')'>",
            "#{id}",
            "</foreach>",
            "</script>"})
    int updateStatusByIds(@Param("ids") List<Long> ids, @Param("status") Integer status);

    default List<ImChatMessageDO> selectListByChatIdAndSequenceGt(Long chatId, Long lastSequence, Integer limit) {
        return selectList(new LambdaQueryWrapperX<ImChatMessageDO>()
                .eq(ImChatMessageDO::getChatId, chatId)
                .gt(ImChatMessageDO::getSequence, lastSequence)
                .orderByAsc(ImChatMessageDO::getSequence)
                .last("LIMIT " + limit));
    }

    @Select({"<script>",
            "SELECT m.*",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "ORDER BY m.sequence DESC",
            "LIMIT #{limit}",
            "</script>"})
    List<ImChatMessageDO> selectVisibleLatestByUser(@Param("tenantId") Long tenantId,
                                                    @Param("userId") Long userId,
                                                    @Param("chatId") Long chatId,
                                                    @Param("limit") Integer limit);

    @Select({"<script>",
            "SELECT m.*",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND m.sequence &lt; #{beforeSequence}",
            "ORDER BY m.sequence DESC",
            "LIMIT #{limit}",
            "</script>"})
    List<ImChatMessageDO> selectVisibleBeforeSequenceByUser(@Param("tenantId") Long tenantId,
                                                            @Param("userId") Long userId,
                                                            @Param("chatId") Long chatId,
                                                            @Param("beforeSequence") Long beforeSequence,
                                                            @Param("limit") Integer limit);

    @Select({"<script>",
            "SELECT m.*",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND m.sequence &gt;= #{anchorSequence}",
            "ORDER BY m.sequence ASC",
            "LIMIT #{limit}",
            "</script>"})
    List<ImChatMessageDO> selectVisibleAfterOrEqualSequenceByUser(@Param("tenantId") Long tenantId,
                                                                  @Param("userId") Long userId,
                                                                  @Param("chatId") Long chatId,
                                                                  @Param("anchorSequence") Long anchorSequence,
                                                                  @Param("limit") Integer limit);

    @Select({"<script>",
            "SELECT m.sequence",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.id = #{messageId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "LIMIT 1",
            "</script>"})
    Long selectVisibleSequenceByMessageId(@Param("tenantId") Long tenantId,
                                          @Param("userId") Long userId,
                                          @Param("chatId") Long chatId,
                                          @Param("messageId") Long messageId);

    @Select({"<script>",
            "SELECT m.sequence",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.sequence = #{sequence}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "LIMIT 1",
            "</script>"})
    Long selectVisibleSequenceBySequence(@Param("tenantId") Long tenantId,
                                         @Param("userId") Long userId,
                                         @Param("chatId") Long chatId,
                                         @Param("sequence") Long sequence);

    @Select({"<script>",
            "SELECT COUNT(1)",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND m.sequence &lt; #{sequence}",
            "</script>"})
    Long countVisibleOlderThanSequence(@Param("tenantId") Long tenantId,
                                       @Param("userId") Long userId,
                                       @Param("chatId") Long chatId,
                                       @Param("sequence") Long sequence);

    @Select({"<script>",
            "SELECT COUNT(1)",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.chat_id = #{chatId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND m.sequence &gt; #{sequence}",
            "</script>"})
    Long countVisibleNewerThanSequence(@Param("tenantId") Long tenantId,
                                       @Param("userId") Long userId,
                                       @Param("chatId") Long chatId,
                                       @Param("sequence") Long sequence);

    /**
     * 根据客户端消息ID查询消息（用于幂等重发）
     */
    default ImChatMessageDO selectByClientMessageId(String clientMessageId) {
        return selectOne(new LambdaQueryWrapperX<ImChatMessageDO>()
                .eq(ImChatMessageDO::getClientMessageId, clientMessageId));
    }

    @Select({"<script>",
            "SELECT COUNT(1)",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND (m.status IS NULL OR m.status != 6)",
            "<if test='chatId != null'>",
            "  AND m.chat_id = #{chatId}",
            "</if>",
            "<if test='keyword != null and keyword != \"\"'>",
            "  AND m.content LIKE CONCAT('%', #{keyword}, '%')",
            "</if>",
            "<if test='messageType != null'>",
            "  AND m.message_type = #{messageType}",
            "</if>",
            "<if test='messageTypeList != null and messageTypeList.size > 0'>",
            "  AND m.message_type IN",
            "  <foreach collection='messageTypeList' item='mt' open='(' separator=',' close=')'>",
            "    #{mt}",
            "  </foreach>",
            "</if>",
            "<if test='startTime != null'>",
            "  AND m.send_time &gt;= #{startTime}",
            "</if>",
            "<if test='endTime != null'>",
            "  AND m.send_time &lt;= #{endTime}",
            "</if>",
            "<if test='onlyLink != null and onlyLink == true'>",
            "  AND (",
            "    (m.content LIKE '%http://%') OR (m.content LIKE '%https://%') OR (m.content LIKE '%www.%')",
            "  )",
            "</if>",
            "</script>"})
    Long countSearchPageByUser(@Param("tenantId") Long tenantId,
                               @Param("userId") Long userId,
                               @Param("chatId") Long chatId,
                               @Param("keyword") String keyword,
                               @Param("messageType") Integer messageType,
                               @Param("messageTypeList") List<Integer> messageTypeList,
                               @Param("startTime") java.time.LocalDateTime startTime,
                               @Param("endTime") java.time.LocalDateTime endTime,
                               @Param("onlyLink") Boolean onlyLink);

    @Select({"<script>",
            "SELECT m.*",
            "FROM im_chat_message m",
            "JOIN im_chat_user cu ON cu.chat_id = m.chat_id",
            "  AND cu.tenant_id = #{tenantId}",
            "  AND cu.user_id = #{userId}",
            "  AND cu.deleted = 0",
            "  AND cu.deleted_by_user = 0",
            "LEFT JOIN im_chat_clear_watermark cw ON cw.chat_id = m.chat_id",
            "  AND cw.tenant_id = #{tenantId}",
            "  AND cw.user_id = #{userId}",
            "  AND cw.deleted = 0",
            "LEFT JOIN im_chat_message_tombstone t ON t.message_id = m.id",
            "  AND t.chat_id = m.chat_id",
            "  AND t.tenant_id = #{tenantId}",
            "  AND t.user_id = #{userId}",
            "  AND t.deleted = 0",
            "WHERE m.tenant_id = #{tenantId}",
            "  AND m.deleted = 0",
            "  AND t.id IS NULL",
            "  AND (cw.clear_sequence IS NULL OR m.sequence &gt; cw.clear_sequence)",
            "  AND m.send_time &lt;= IFNULL(cu.left_at, '9999-12-31 23:59:59')",
            "  AND (m.status IS NULL OR m.status != 6)",
            "<if test='chatId != null'>",
            "  AND m.chat_id = #{chatId}",
            "</if>",
            "<if test='keyword != null and keyword != \"\"'>",
            "  AND m.content LIKE CONCAT('%', #{keyword}, '%')",
            "</if>",
            "<if test='messageType != null'>",
            "  AND m.message_type = #{messageType}",
            "</if>",
            "<if test='messageTypeList != null and messageTypeList.size > 0'>",
            "  AND m.message_type IN",
            "  <foreach collection='messageTypeList' item='mt' open='(' separator=',' close=')'>",
            "    #{mt}",
            "  </foreach>",
            "</if>",
            "<if test='startTime != null'>",
            "  AND m.send_time &gt;= #{startTime}",
            "</if>",
            "<if test='endTime != null'>",
            "  AND m.send_time &lt;= #{endTime}",
            "</if>",
            "<if test='onlyLink != null and onlyLink == true'>",
            "  AND (",
            "    (m.content LIKE '%http://%') OR (m.content LIKE '%https://%') OR (m.content LIKE '%www.%')",
            "  )",
            "</if>",
            "ORDER BY m.send_time DESC, m.id DESC",
            "LIMIT #{limit} OFFSET #{offset}",
            "</script>"})
    List<ImChatMessageDO> selectSearchPageByUser(@Param("tenantId") Long tenantId,
                                                 @Param("userId") Long userId,
                                                  @Param("chatId") Long chatId,
                                                  @Param("keyword") String keyword,
                                                  @Param("messageType") Integer messageType,
                                                  @Param("messageTypeList") List<Integer> messageTypeList,
                                                  @Param("startTime") java.time.LocalDateTime startTime,
                                                  @Param("endTime") java.time.LocalDateTime endTime,
                                                  @Param("offset") Long offset,
                                                 @Param("limit") Long limit,
                                                 @Param("onlyLink") Boolean onlyLink);

}
