// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface AckMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AckMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 被确认的消息ID
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <pre>
   * 会话ID（可选）
   * </pre>
   *
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <pre>
   * 被确认的序列号（可选）
   * </pre>
   *
   * <code>int64 sequence = 3;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <pre>
   * ACK 类型：RECEIVED / READ 等（phase1 使用 RECEIVED）
   * </pre>
   *
   * <code>string ackType = 4;</code>
   * @return The ackType.
   */
  java.lang.String getAckType();
  /**
   * <pre>
   * ACK 类型：RECEIVED / READ 等（phase1 使用 RECEIVED）
   * </pre>
   *
   * <code>string ackType = 4;</code>
   * @return The bytes for ackType.
   */
  com.google.protobuf.ByteString
      getAckTypeBytes();

  /**
   * <pre>
   * 客户端收到时间（毫秒）
   * </pre>
   *
   * <code>int64 clientReceivedAt = 5;</code>
   * @return The clientReceivedAt.
   */
  long getClientReceivedAt();

  /**
   * <pre>
   * 原消息时间戳（可选，用于计算端到端延迟）
   * </pre>
   *
   * <code>int64 originalTimestamp = 6;</code>
   * @return The originalTimestamp.
   */
  long getOriginalTimestamp();
}
