// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface BadgeUpdateMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BadgeUpdateMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 总未读数
   * </pre>
   *
   * <code>int32 unreadCount = 1;</code>
   * @return The unreadCount.
   */
  int getUnreadCount();

  /**
   * <pre>
   * 会话角标列表
   * </pre>
   *
   * <code>repeated .ConversationBadge conversationBadges = 2;</code>
   */
  java.util.List<com.shengyu.framework.websocket.core.protocol.ConversationBadge> 
      getConversationBadgesList();
  /**
   * <pre>
   * 会话角标列表
   * </pre>
   *
   * <code>repeated .ConversationBadge conversationBadges = 2;</code>
   */
  com.shengyu.framework.websocket.core.protocol.ConversationBadge getConversationBadges(int index);
  /**
   * <pre>
   * 会话角标列表
   * </pre>
   *
   * <code>repeated .ConversationBadge conversationBadges = 2;</code>
   */
  int getConversationBadgesCount();
  /**
   * <pre>
   * 会话角标列表
   * </pre>
   *
   * <code>repeated .ConversationBadge conversationBadges = 2;</code>
   */
  java.util.List<? extends com.shengyu.framework.websocket.core.protocol.ConversationBadgeOrBuilder> 
      getConversationBadgesOrBuilderList();
  /**
   * <pre>
   * 会话角标列表
   * </pre>
   *
   * <code>repeated .ConversationBadge conversationBadges = 2;</code>
   */
  com.shengyu.framework.websocket.core.protocol.ConversationBadgeOrBuilder getConversationBadgesOrBuilder(
      int index);

  /**
   * <pre>
   * 菜单角标列表
   * </pre>
   *
   * <code>repeated .MenuBadge menuBadges = 3;</code>
   */
  java.util.List<com.shengyu.framework.websocket.core.protocol.MenuBadge> 
      getMenuBadgesList();
  /**
   * <pre>
   * 菜单角标列表
   * </pre>
   *
   * <code>repeated .MenuBadge menuBadges = 3;</code>
   */
  com.shengyu.framework.websocket.core.protocol.MenuBadge getMenuBadges(int index);
  /**
   * <pre>
   * 菜单角标列表
   * </pre>
   *
   * <code>repeated .MenuBadge menuBadges = 3;</code>
   */
  int getMenuBadgesCount();
  /**
   * <pre>
   * 菜单角标列表
   * </pre>
   *
   * <code>repeated .MenuBadge menuBadges = 3;</code>
   */
  java.util.List<? extends com.shengyu.framework.websocket.core.protocol.MenuBadgeOrBuilder> 
      getMenuBadgesOrBuilderList();
  /**
   * <pre>
   * 菜单角标列表
   * </pre>
   *
   * <code>repeated .MenuBadge menuBadges = 3;</code>
   */
  com.shengyu.framework.websocket.core.protocol.MenuBadgeOrBuilder getMenuBadgesOrBuilder(
      int index);

  /**
   * <pre>
   * 是否为增量推送（true 时 conversationBadges 仅包含变化的会话）
   * </pre>
   *
   * <code>bool incremental = 4;</code>
   * @return The incremental.
   */
  boolean getIncremental();
}
