// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 通话信令消息
 * </pre>
 *
 * Protobuf type {@code CallSignalMessage}
 */
public final class CallSignalMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CallSignalMessage)
    CallSignalMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallSignalMessage.newBuilder() to construct.
  private CallSignalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallSignalMessage() {
    callId_ = "";
    rejectReason_ = "";
    extraData_ = "";
    inviteeIds_ = emptyLongList();
    roomId_ = "";
    janusToken_ = "";
    deviceId_ = "";
    deviceName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallSignalMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_CallSignalMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_CallSignalMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.CallSignalMessage.class, com.shengyu.framework.websocket.core.protocol.CallSignalMessage.Builder.class);
  }

  public static final int CALLID_FIELD_NUMBER = 1;
  private volatile java.lang.Object callId_;
  /**
   * <pre>
   * 通话ID
   * </pre>
   *
   * <code>string callId = 1;</code>
   * @return The callId.
   */
  @java.lang.Override
  public java.lang.String getCallId() {
    java.lang.Object ref = callId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 通话ID
   * </pre>
   *
   * <code>string callId = 1;</code>
   * @return The bytes for callId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallIdBytes() {
    java.lang.Object ref = callId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLTYPE_FIELD_NUMBER = 2;
  private int callType_;
  /**
   * <pre>
   * 通话类型（1-语音 2-视频）
   * </pre>
   *
   * <code>int32 callType = 2;</code>
   * @return The callType.
   */
  @java.lang.Override
  public int getCallType() {
    return callType_;
  }

  public static final int SIGNALTYPE_FIELD_NUMBER = 3;
  private int signalType_;
  /**
   * <pre>
   * 信令类型（1-呼叫 2-接听 3-拒绝 4-挂断 5-忙线 6-切换摄像头）
   * </pre>
   *
   * <code>int32 signalType = 3;</code>
   * @return The signalType.
   */
  @java.lang.Override
  public int getSignalType() {
    return signalType_;
  }

  public static final int CALLERID_FIELD_NUMBER = 4;
  private long callerId_;
  /**
   * <pre>
   * 呼叫方ID
   * </pre>
   *
   * <code>int64 callerId = 4;</code>
   * @return The callerId.
   */
  @java.lang.Override
  public long getCallerId() {
    return callerId_;
  }

  public static final int CALLEEID_FIELD_NUMBER = 5;
  private long calleeId_;
  /**
   * <pre>
   * 接听方ID
   * </pre>
   *
   * <code>int64 calleeId = 5;</code>
   * @return The calleeId.
   */
  @java.lang.Override
  public long getCalleeId() {
    return calleeId_;
  }

  public static final int REJECTREASON_FIELD_NUMBER = 6;
  private volatile java.lang.Object rejectReason_;
  /**
   * <pre>
   * 拒绝原因（信令类型为拒绝时使用）
   * </pre>
   *
   * <code>string rejectReason = 6;</code>
   * @return The rejectReason.
   */
  @java.lang.Override
  public java.lang.String getRejectReason() {
    java.lang.Object ref = rejectReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rejectReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 拒绝原因（信令类型为拒绝时使用）
   * </pre>
   *
   * <code>string rejectReason = 6;</code>
   * @return The bytes for rejectReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRejectReasonBytes() {
    java.lang.Object ref = rejectReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rejectReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRADATA_FIELD_NUMBER = 7;
  private volatile java.lang.Object extraData_;
  /**
   * <pre>
   * 扩展数据（JSON格式，用于传递WebRTC信令）
   * </pre>
   *
   * <code>string extraData = 7;</code>
   * @return The extraData.
   */
  @java.lang.Override
  public java.lang.String getExtraData() {
    java.lang.Object ref = extraData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extraData_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展数据（JSON格式，用于传递WebRTC信令）
   * </pre>
   *
   * <code>string extraData = 7;</code>
   * @return The bytes for extraData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtraDataBytes() {
    java.lang.Object ref = extraData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extraData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPID_FIELD_NUMBER = 8;
  private long groupId_;
  /**
   * <pre>
   * 群组ID（群通话时使用）
   * </pre>
   *
   * <code>int64 groupId = 8;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int INVITEEIDS_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.LongList inviteeIds_;
  /**
   * <pre>
   * 被邀请人列表（群通话时使用）
   * </pre>
   *
   * <code>repeated int64 inviteeIds = 9;</code>
   * @return A list containing the inviteeIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getInviteeIdsList() {
    return inviteeIds_;
  }
  /**
   * <pre>
   * 被邀请人列表（群通话时使用）
   * </pre>
   *
   * <code>repeated int64 inviteeIds = 9;</code>
   * @return The count of inviteeIds.
   */
  public int getInviteeIdsCount() {
    return inviteeIds_.size();
  }
  /**
   * <pre>
   * 被邀请人列表（群通话时使用）
   * </pre>
   *
   * <code>repeated int64 inviteeIds = 9;</code>
   * @param index The index of the element to return.
   * @return The inviteeIds at the given index.
   */
  public long getInviteeIds(int index) {
    return inviteeIds_.getLong(index);
  }
  private int inviteeIdsMemoizedSerializedSize = -1;

  public static final int ROOMID_FIELD_NUMBER = 10;
  private volatile java.lang.Object roomId_;
  /**
   * <pre>
   * Janus Room ID（通话建立后生成）
   * </pre>
   *
   * <code>string roomId = 10;</code>
   * @return The roomId.
   */
  @java.lang.Override
  public java.lang.String getRoomId() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Janus Room ID（通话建立后生成）
   * </pre>
   *
   * <code>string roomId = 10;</code>
   * @return The bytes for roomId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomIdBytes() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JANUSTOKEN_FIELD_NUMBER = 11;
  private volatile java.lang.Object janusToken_;
  /**
   * <pre>
   * Janus Token（客户端加入房间用）
   * </pre>
   *
   * <code>string janusToken = 11;</code>
   * @return The janusToken.
   */
  @java.lang.Override
  public java.lang.String getJanusToken() {
    java.lang.Object ref = janusToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      janusToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Janus Token（客户端加入房间用）
   * </pre>
   *
   * <code>string janusToken = 11;</code>
   * @return The bytes for janusToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJanusTokenBytes() {
    java.lang.Object ref = janusToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      janusToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIATETIME_FIELD_NUMBER = 12;
  private long initiateTime_;
  /**
   * <pre>
   * 通话发起时间戳（毫秒）
   * </pre>
   *
   * <code>int64 initiateTime = 12;</code>
   * @return The initiateTime.
   */
  @java.lang.Override
  public long getInitiateTime() {
    return initiateTime_;
  }

  public static final int DEVICEID_FIELD_NUMBER = 13;
  private volatile java.lang.Object deviceId_;
  /**
   * <pre>
   * 设备ID（用于多设备区分）
   * </pre>
   *
   * <code>string deviceId = 13;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备ID（用于多设备区分）
   * </pre>
   *
   * <code>string deviceId = 13;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICENAME_FIELD_NUMBER = 14;
  private volatile java.lang.Object deviceName_;
  /**
   * <pre>
   * 设备名称（用于多设备显示）
   * </pre>
   *
   * <code>string deviceName = 14;</code>
   * @return The deviceName.
   */
  @java.lang.Override
  public java.lang.String getDeviceName() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备名称（用于多设备显示）
   * </pre>
   *
   * <code>string deviceName = 14;</code>
   * @return The bytes for deviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(callId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, callId_);
    }
    if (callType_ != 0) {
      output.writeInt32(2, callType_);
    }
    if (signalType_ != 0) {
      output.writeInt32(3, signalType_);
    }
    if (callerId_ != 0L) {
      output.writeInt64(4, callerId_);
    }
    if (calleeId_ != 0L) {
      output.writeInt64(5, calleeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rejectReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, rejectReason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extraData_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extraData_);
    }
    if (groupId_ != 0L) {
      output.writeInt64(8, groupId_);
    }
    if (getInviteeIdsList().size() > 0) {
      output.writeUInt32NoTag(74);
      output.writeUInt32NoTag(inviteeIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < inviteeIds_.size(); i++) {
      output.writeInt64NoTag(inviteeIds_.getLong(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, roomId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(janusToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, janusToken_);
    }
    if (initiateTime_ != 0L) {
      output.writeInt64(12, initiateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, deviceName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(callId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, callId_);
    }
    if (callType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, callType_);
    }
    if (signalType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, signalType_);
    }
    if (callerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, callerId_);
    }
    if (calleeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, calleeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rejectReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, rejectReason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extraData_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extraData_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, groupId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inviteeIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(inviteeIds_.getLong(i));
      }
      size += dataSize;
      if (!getInviteeIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      inviteeIdsMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, roomId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(janusToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, janusToken_);
    }
    if (initiateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, initiateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, deviceName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.CallSignalMessage)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.CallSignalMessage other = (com.shengyu.framework.websocket.core.protocol.CallSignalMessage) obj;

    if (!getCallId()
        .equals(other.getCallId())) return false;
    if (getCallType()
        != other.getCallType()) return false;
    if (getSignalType()
        != other.getSignalType()) return false;
    if (getCallerId()
        != other.getCallerId()) return false;
    if (getCalleeId()
        != other.getCalleeId()) return false;
    if (!getRejectReason()
        .equals(other.getRejectReason())) return false;
    if (!getExtraData()
        .equals(other.getExtraData())) return false;
    if (getGroupId()
        != other.getGroupId()) return false;
    if (!getInviteeIdsList()
        .equals(other.getInviteeIdsList())) return false;
    if (!getRoomId()
        .equals(other.getRoomId())) return false;
    if (!getJanusToken()
        .equals(other.getJanusToken())) return false;
    if (getInitiateTime()
        != other.getInitiateTime()) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getDeviceName()
        .equals(other.getDeviceName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CALLID_FIELD_NUMBER;
    hash = (53 * hash) + getCallId().hashCode();
    hash = (37 * hash) + CALLTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCallType();
    hash = (37 * hash) + SIGNALTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSignalType();
    hash = (37 * hash) + CALLERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCallerId());
    hash = (37 * hash) + CALLEEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCalleeId());
    hash = (37 * hash) + REJECTREASON_FIELD_NUMBER;
    hash = (53 * hash) + getRejectReason().hashCode();
    hash = (37 * hash) + EXTRADATA_FIELD_NUMBER;
    hash = (53 * hash) + getExtraData().hashCode();
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    if (getInviteeIdsCount() > 0) {
      hash = (37 * hash) + INVITEEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getInviteeIdsList().hashCode();
    }
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId().hashCode();
    hash = (37 * hash) + JANUSTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getJanusToken().hashCode();
    hash = (37 * hash) + INITIATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInitiateTime());
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.CallSignalMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 通话信令消息
   * </pre>
   *
   * Protobuf type {@code CallSignalMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CallSignalMessage)
      com.shengyu.framework.websocket.core.protocol.CallSignalMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_CallSignalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_CallSignalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.CallSignalMessage.class, com.shengyu.framework.websocket.core.protocol.CallSignalMessage.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.CallSignalMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      callId_ = "";

      callType_ = 0;

      signalType_ = 0;

      callerId_ = 0L;

      calleeId_ = 0L;

      rejectReason_ = "";

      extraData_ = "";

      groupId_ = 0L;

      inviteeIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      roomId_ = "";

      janusToken_ = "";

      initiateTime_ = 0L;

      deviceId_ = "";

      deviceName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_CallSignalMessage_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.CallSignalMessage getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.CallSignalMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.CallSignalMessage build() {
      com.shengyu.framework.websocket.core.protocol.CallSignalMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.CallSignalMessage buildPartial() {
      com.shengyu.framework.websocket.core.protocol.CallSignalMessage result = new com.shengyu.framework.websocket.core.protocol.CallSignalMessage(this);
      int from_bitField0_ = bitField0_;
      result.callId_ = callId_;
      result.callType_ = callType_;
      result.signalType_ = signalType_;
      result.callerId_ = callerId_;
      result.calleeId_ = calleeId_;
      result.rejectReason_ = rejectReason_;
      result.extraData_ = extraData_;
      result.groupId_ = groupId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        inviteeIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.inviteeIds_ = inviteeIds_;
      result.roomId_ = roomId_;
      result.janusToken_ = janusToken_;
      result.initiateTime_ = initiateTime_;
      result.deviceId_ = deviceId_;
      result.deviceName_ = deviceName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.CallSignalMessage) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.CallSignalMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.CallSignalMessage other) {
      if (other == com.shengyu.framework.websocket.core.protocol.CallSignalMessage.getDefaultInstance()) return this;
      if (!other.getCallId().isEmpty()) {
        callId_ = other.callId_;
        onChanged();
      }
      if (other.getCallType() != 0) {
        setCallType(other.getCallType());
      }
      if (other.getSignalType() != 0) {
        setSignalType(other.getSignalType());
      }
      if (other.getCallerId() != 0L) {
        setCallerId(other.getCallerId());
      }
      if (other.getCalleeId() != 0L) {
        setCalleeId(other.getCalleeId());
      }
      if (!other.getRejectReason().isEmpty()) {
        rejectReason_ = other.rejectReason_;
        onChanged();
      }
      if (!other.getExtraData().isEmpty()) {
        extraData_ = other.extraData_;
        onChanged();
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (!other.inviteeIds_.isEmpty()) {
        if (inviteeIds_.isEmpty()) {
          inviteeIds_ = other.inviteeIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureInviteeIdsIsMutable();
          inviteeIds_.addAll(other.inviteeIds_);
        }
        onChanged();
      }
      if (!other.getRoomId().isEmpty()) {
        roomId_ = other.roomId_;
        onChanged();
      }
      if (!other.getJanusToken().isEmpty()) {
        janusToken_ = other.janusToken_;
        onChanged();
      }
      if (other.getInitiateTime() != 0L) {
        setInitiateTime(other.getInitiateTime());
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getDeviceName().isEmpty()) {
        deviceName_ = other.deviceName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              callId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              callType_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              signalType_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              callerId_ = input.readInt64();

              break;
            } // case 32
            case 40: {
              calleeId_ = input.readInt64();

              break;
            } // case 40
            case 50: {
              rejectReason_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              extraData_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              groupId_ = input.readInt64();

              break;
            } // case 64
            case 72: {
              long v = input.readInt64();
              ensureInviteeIdsIsMutable();
              inviteeIds_.addLong(v);
              break;
            } // case 72
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureInviteeIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                inviteeIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 74
            case 82: {
              roomId_ = input.readStringRequireUtf8();

              break;
            } // case 82
            case 90: {
              janusToken_ = input.readStringRequireUtf8();

              break;
            } // case 90
            case 96: {
              initiateTime_ = input.readInt64();

              break;
            } // case 96
            case 106: {
              deviceId_ = input.readStringRequireUtf8();

              break;
            } // case 106
            case 114: {
              deviceName_ = input.readStringRequireUtf8();

              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object callId_ = "";
    /**
     * <pre>
     * 通话ID
     * </pre>
     *
     * <code>string callId = 1;</code>
     * @return The callId.
     */
    public java.lang.String getCallId() {
      java.lang.Object ref = callId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 通话ID
     * </pre>
     *
     * <code>string callId = 1;</code>
     * @return The bytes for callId.
     */
    public com.google.protobuf.ByteString
        getCallIdBytes() {
      java.lang.Object ref = callId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 通话ID
     * </pre>
     *
     * <code>string callId = 1;</code>
     * @param value The callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通话ID
     * </pre>
     *
     * <code>string callId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallId() {
      
      callId_ = getDefaultInstance().getCallId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通话ID
     * </pre>
     *
     * <code>string callId = 1;</code>
     * @param value The bytes for callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callId_ = value;
      onChanged();
      return this;
    }

    private int callType_ ;
    /**
     * <pre>
     * 通话类型（1-语音 2-视频）
     * </pre>
     *
     * <code>int32 callType = 2;</code>
     * @return The callType.
     */
    @java.lang.Override
    public int getCallType() {
      return callType_;
    }
    /**
     * <pre>
     * 通话类型（1-语音 2-视频）
     * </pre>
     *
     * <code>int32 callType = 2;</code>
     * @param value The callType to set.
     * @return This builder for chaining.
     */
    public Builder setCallType(int value) {
      
      callType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通话类型（1-语音 2-视频）
     * </pre>
     *
     * <code>int32 callType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallType() {
      
      callType_ = 0;
      onChanged();
      return this;
    }

    private int signalType_ ;
    /**
     * <pre>
     * 信令类型（1-呼叫 2-接听 3-拒绝 4-挂断 5-忙线 6-切换摄像头）
     * </pre>
     *
     * <code>int32 signalType = 3;</code>
     * @return The signalType.
     */
    @java.lang.Override
    public int getSignalType() {
      return signalType_;
    }
    /**
     * <pre>
     * 信令类型（1-呼叫 2-接听 3-拒绝 4-挂断 5-忙线 6-切换摄像头）
     * </pre>
     *
     * <code>int32 signalType = 3;</code>
     * @param value The signalType to set.
     * @return This builder for chaining.
     */
    public Builder setSignalType(int value) {
      
      signalType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信令类型（1-呼叫 2-接听 3-拒绝 4-挂断 5-忙线 6-切换摄像头）
     * </pre>
     *
     * <code>int32 signalType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignalType() {
      
      signalType_ = 0;
      onChanged();
      return this;
    }

    private long callerId_ ;
    /**
     * <pre>
     * 呼叫方ID
     * </pre>
     *
     * <code>int64 callerId = 4;</code>
     * @return The callerId.
     */
    @java.lang.Override
    public long getCallerId() {
      return callerId_;
    }
    /**
     * <pre>
     * 呼叫方ID
     * </pre>
     *
     * <code>int64 callerId = 4;</code>
     * @param value The callerId to set.
     * @return This builder for chaining.
     */
    public Builder setCallerId(long value) {
      
      callerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 呼叫方ID
     * </pre>
     *
     * <code>int64 callerId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallerId() {
      
      callerId_ = 0L;
      onChanged();
      return this;
    }

    private long calleeId_ ;
    /**
     * <pre>
     * 接听方ID
     * </pre>
     *
     * <code>int64 calleeId = 5;</code>
     * @return The calleeId.
     */
    @java.lang.Override
    public long getCalleeId() {
      return calleeId_;
    }
    /**
     * <pre>
     * 接听方ID
     * </pre>
     *
     * <code>int64 calleeId = 5;</code>
     * @param value The calleeId to set.
     * @return This builder for chaining.
     */
    public Builder setCalleeId(long value) {
      
      calleeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接听方ID
     * </pre>
     *
     * <code>int64 calleeId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCalleeId() {
      
      calleeId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object rejectReason_ = "";
    /**
     * <pre>
     * 拒绝原因（信令类型为拒绝时使用）
     * </pre>
     *
     * <code>string rejectReason = 6;</code>
     * @return The rejectReason.
     */
    public java.lang.String getRejectReason() {
      java.lang.Object ref = rejectReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rejectReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 拒绝原因（信令类型为拒绝时使用）
     * </pre>
     *
     * <code>string rejectReason = 6;</code>
     * @return The bytes for rejectReason.
     */
    public com.google.protobuf.ByteString
        getRejectReasonBytes() {
      java.lang.Object ref = rejectReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rejectReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 拒绝原因（信令类型为拒绝时使用）
     * </pre>
     *
     * <code>string rejectReason = 6;</code>
     * @param value The rejectReason to set.
     * @return This builder for chaining.
     */
    public Builder setRejectReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rejectReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 拒绝原因（信令类型为拒绝时使用）
     * </pre>
     *
     * <code>string rejectReason = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectReason() {
      
      rejectReason_ = getDefaultInstance().getRejectReason();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 拒绝原因（信令类型为拒绝时使用）
     * </pre>
     *
     * <code>string rejectReason = 6;</code>
     * @param value The bytes for rejectReason to set.
     * @return This builder for chaining.
     */
    public Builder setRejectReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rejectReason_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extraData_ = "";
    /**
     * <pre>
     * 扩展数据（JSON格式，用于传递WebRTC信令）
     * </pre>
     *
     * <code>string extraData = 7;</code>
     * @return The extraData.
     */
    public java.lang.String getExtraData() {
      java.lang.Object ref = extraData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 扩展数据（JSON格式，用于传递WebRTC信令）
     * </pre>
     *
     * <code>string extraData = 7;</code>
     * @return The bytes for extraData.
     */
    public com.google.protobuf.ByteString
        getExtraDataBytes() {
      java.lang.Object ref = extraData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展数据（JSON格式，用于传递WebRTC信令）
     * </pre>
     *
     * <code>string extraData = 7;</code>
     * @param value The extraData to set.
     * @return This builder for chaining.
     */
    public Builder setExtraData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extraData_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展数据（JSON格式，用于传递WebRTC信令）
     * </pre>
     *
     * <code>string extraData = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtraData() {
      
      extraData_ = getDefaultInstance().getExtraData();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展数据（JSON格式，用于传递WebRTC信令）
     * </pre>
     *
     * <code>string extraData = 7;</code>
     * @param value The bytes for extraData to set.
     * @return This builder for chaining.
     */
    public Builder setExtraDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extraData_ = value;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <pre>
     * 群组ID（群通话时使用）
     * </pre>
     *
     * <code>int64 groupId = 8;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <pre>
     * 群组ID（群通话时使用）
     * </pre>
     *
     * <code>int64 groupId = 8;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {
      
      groupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 群组ID（群通话时使用）
     * </pre>
     *
     * <code>int64 groupId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList inviteeIds_ = emptyLongList();
    private void ensureInviteeIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        inviteeIds_ = mutableCopy(inviteeIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @return A list containing the inviteeIds.
     */
    public java.util.List<java.lang.Long>
        getInviteeIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(inviteeIds_) : inviteeIds_;
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @return The count of inviteeIds.
     */
    public int getInviteeIdsCount() {
      return inviteeIds_.size();
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @param index The index of the element to return.
     * @return The inviteeIds at the given index.
     */
    public long getInviteeIds(int index) {
      return inviteeIds_.getLong(index);
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @param index The index to set the value at.
     * @param value The inviteeIds to set.
     * @return This builder for chaining.
     */
    public Builder setInviteeIds(
        int index, long value) {
      ensureInviteeIdsIsMutable();
      inviteeIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @param value The inviteeIds to add.
     * @return This builder for chaining.
     */
    public Builder addInviteeIds(long value) {
      ensureInviteeIdsIsMutable();
      inviteeIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @param values The inviteeIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllInviteeIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureInviteeIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inviteeIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被邀请人列表（群通话时使用）
     * </pre>
     *
     * <code>repeated int64 inviteeIds = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearInviteeIds() {
      inviteeIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.lang.Object roomId_ = "";
    /**
     * <pre>
     * Janus Room ID（通话建立后生成）
     * </pre>
     *
     * <code>string roomId = 10;</code>
     * @return The roomId.
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Janus Room ID（通话建立后生成）
     * </pre>
     *
     * <code>string roomId = 10;</code>
     * @return The bytes for roomId.
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Janus Room ID（通话建立后生成）
     * </pre>
     *
     * <code>string roomId = 10;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Janus Room ID（通话建立后生成）
     * </pre>
     *
     * <code>string roomId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      
      roomId_ = getDefaultInstance().getRoomId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Janus Room ID（通话建立后生成）
     * </pre>
     *
     * <code>string roomId = 10;</code>
     * @param value The bytes for roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object janusToken_ = "";
    /**
     * <pre>
     * Janus Token（客户端加入房间用）
     * </pre>
     *
     * <code>string janusToken = 11;</code>
     * @return The janusToken.
     */
    public java.lang.String getJanusToken() {
      java.lang.Object ref = janusToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        janusToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Janus Token（客户端加入房间用）
     * </pre>
     *
     * <code>string janusToken = 11;</code>
     * @return The bytes for janusToken.
     */
    public com.google.protobuf.ByteString
        getJanusTokenBytes() {
      java.lang.Object ref = janusToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        janusToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Janus Token（客户端加入房间用）
     * </pre>
     *
     * <code>string janusToken = 11;</code>
     * @param value The janusToken to set.
     * @return This builder for chaining.
     */
    public Builder setJanusToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      janusToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Janus Token（客户端加入房间用）
     * </pre>
     *
     * <code>string janusToken = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearJanusToken() {
      
      janusToken_ = getDefaultInstance().getJanusToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Janus Token（客户端加入房间用）
     * </pre>
     *
     * <code>string janusToken = 11;</code>
     * @param value The bytes for janusToken to set.
     * @return This builder for chaining.
     */
    public Builder setJanusTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      janusToken_ = value;
      onChanged();
      return this;
    }

    private long initiateTime_ ;
    /**
     * <pre>
     * 通话发起时间戳（毫秒）
     * </pre>
     *
     * <code>int64 initiateTime = 12;</code>
     * @return The initiateTime.
     */
    @java.lang.Override
    public long getInitiateTime() {
      return initiateTime_;
    }
    /**
     * <pre>
     * 通话发起时间戳（毫秒）
     * </pre>
     *
     * <code>int64 initiateTime = 12;</code>
     * @param value The initiateTime to set.
     * @return This builder for chaining.
     */
    public Builder setInitiateTime(long value) {
      
      initiateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通话发起时间戳（毫秒）
     * </pre>
     *
     * <code>int64 initiateTime = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiateTime() {
      
      initiateTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * 设备ID（用于多设备区分）
     * </pre>
     *
     * <code>string deviceId = 13;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备ID（用于多设备区分）
     * </pre>
     *
     * <code>string deviceId = 13;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备ID（用于多设备区分）
     * </pre>
     *
     * <code>string deviceId = 13;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID（用于多设备区分）
     * </pre>
     *
     * <code>string deviceId = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID（用于多设备区分）
     * </pre>
     *
     * <code>string deviceId = 13;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceName_ = "";
    /**
     * <pre>
     * 设备名称（用于多设备显示）
     * </pre>
     *
     * <code>string deviceName = 14;</code>
     * @return The deviceName.
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备名称（用于多设备显示）
     * </pre>
     *
     * <code>string deviceName = 14;</code>
     * @return The bytes for deviceName.
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备名称（用于多设备显示）
     * </pre>
     *
     * <code>string deviceName = 14;</code>
     * @param value The deviceName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备名称（用于多设备显示）
     * </pre>
     *
     * <code>string deviceName = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceName() {
      
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备名称（用于多设备显示）
     * </pre>
     *
     * <code>string deviceName = 14;</code>
     * @param value The bytes for deviceName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CallSignalMessage)
  }

  // @@protoc_insertion_point(class_scope:CallSignalMessage)
  private static final com.shengyu.framework.websocket.core.protocol.CallSignalMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.CallSignalMessage();
  }

  public static com.shengyu.framework.websocket.core.protocol.CallSignalMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallSignalMessage>
      PARSER = new com.google.protobuf.AbstractParser<CallSignalMessage>() {
    @java.lang.Override
    public CallSignalMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CallSignalMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallSignalMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.CallSignalMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

