// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface ConversationBadgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConversationBadge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>int64 conversationId = 1;</code>
   * @return The conversationId.
   */
  long getConversationId();

  /**
   * <pre>
   * 未读数
   * </pre>
   *
   * <code>int32 unreadCount = 2;</code>
   * @return The unreadCount.
   */
  int getUnreadCount();
}
