// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public final class ImMessageProto {
  private ImMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MentionUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MentionUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoiceMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoiceMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadReceiptMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadReceiptMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecallMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecallMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuoteReplyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuoteReplyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TypingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TypingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BadgeUpdateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BadgeUpdateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConversationBadge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConversationBadge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuBadge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MenuBadge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallSignalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallSignalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkflowNotifyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkflowNotifyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkflowButton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkflowButton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TodoReminderMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TodoReminderMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020im_message.proto\"9\n\tImMessage\022\036\n\006heade" +
      "r\030\001 \001(\0132\016.MessageHeader\022\014\n\004body\030\002 \001(\014\"\302\001" +
      "\n\rMessageHeader\022\021\n\tmessageId\030\001 \001(\003\022!\n\013me" +
      "ssageType\030\002 \001(\0162\014.MessageType\022\020\n\010senderI" +
      "d\030\003 \001(\003\022\022\n\nreceiverId\030\004 \001(\003\022\017\n\007groupId\030\005" +
      " \001(\003\022\020\n\010tenantId\030\006 \001(\003\022\021\n\ttimestamp\030\007 \001(" +
      "\003\022\020\n\010sequence\030\010 \001(\003\022\r\n\005extra\030\t \001(\t\"o\n\013Au" +
      "thRequest\022\023\n\013accessToken\030\001 \001(\t\022\022\n\ndevice" +
      "Type\030\002 \001(\005\022\020\n\010deviceId\030\003 \001(\t\022\025\n\rclientVe" +
      "rsion\030\004 \001(\t\022\016\n\006locale\030\005 \001(\t\"`\n\014AuthRespo" +
      "nse\022\017\n\007success\030\001 \001(\010\022\014\n\004code\030\002 \001(\005\022\017\n\007me" +
      "ssage\030\003 \001(\t\022\016\n\006userId\030\004 \001(\003\022\020\n\010tenantId\030" +
      "\005 \001(\003\"\207\001\n\nAckMessage\022\021\n\tmessageId\030\001 \001(\003\022" +
      "\016\n\006chatId\030\002 \001(\003\022\020\n\010sequence\030\003 \001(\003\022\017\n\007ack" +
      "Type\030\004 \001(\t\022\030\n\020clientReceivedAt\030\005 \001(\003\022\031\n\021" +
      "originalTimestamp\030\006 \001(\003\"=\n\013AckResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\014\n\004code\030\002 \001(\005\022\017\n\007message" +
      "\030\003 \001(\t\"U\n\013MentionUser\022\016\n\006userId\030\001 \001(\003\022\020\n" +
      "\010nickname\030\002 \001(\t\022\022\n\nstartIndex\030\003 \001(\005\022\020\n\010e" +
      "ndIndex\030\004 \001(\005\"Q\n\013TextMessage\022\017\n\007content\030" +
      "\001 \001(\t\022\021\n\tatUserIds\030\002 \003(\003\022\036\n\010mentions\030\003 \003" +
      "(\0132\014.MentionUser\"p\n\014ImageMessage\022\013\n\003url\030" +
      "\001 \001(\t\022\024\n\014thumbnailUrl\030\002 \001(\t\022\r\n\005width\030\003 \001" +
      "(\005\022\016\n\006height\030\004 \001(\005\022\014\n\004size\030\005 \001(\003\022\020\n\010file" +
      "Name\030\006 \001(\t\";\n\014VoiceMessage\022\013\n\003url\030\001 \001(\t\022" +
      "\020\n\010duration\030\002 \001(\005\022\014\n\004size\030\003 \001(\003\"l\n\014Video" +
      "Message\022\013\n\003url\030\001 \001(\t\022\020\n\010coverUrl\030\002 \001(\t\022\020" +
      "\n\010duration\030\003 \001(\005\022\r\n\005width\030\004 \001(\005\022\016\n\006heigh" +
      "t\030\005 \001(\005\022\014\n\004size\030\006 \001(\003\"L\n\013FileMessage\022\013\n\003" +
      "url\030\001 \001(\t\022\020\n\010fileName\030\002 \001(\t\022\014\n\004size\030\003 \001(" +
      "\003\022\020\n\010fileType\030\004 \001(\t\"G\n\017LocationMessage\022\020" +
      "\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\017\n\007a" +
      "ddress\030\003 \001(\t\"(\n\022ReadReceiptMessage\022\022\n\nme" +
      "ssageIds\030\001 \003(\003\"\"\n\rRecallMessage\022\021\n\tmessa" +
      "geId\030\001 \001(\003\"\272\001\n\021QuoteReplyMessage\022\026\n\016quot" +
      "eMessageId\030\001 \001(\003\022\024\n\014quoteContent\030\002 \001(\t\022\025" +
      "\n\rquoteSenderId\030\003 \001(\003\022\027\n\017quoteSenderName" +
      "\030\004 \001(\t\022\024\n\014replyContent\030\005 \001(\t\022\021\n\tatUserId" +
      "s\030\006 \003(\003\022\036\n\010mentions\030\007 \003(\0132\014.MentionUser\"" +
      "H\n\rTypingMessage\022\024\n\014targetUserId\030\001 \001(\003\022\017" +
      "\n\007groupId\030\002 \001(\003\022\020\n\010isTyping\030\003 \001(\010\"y\n\022Bad" +
      "geUpdateMessage\022\023\n\013unreadCount\030\001 \001(\005\022.\n\022" +
      "conversationBadges\030\002 \003(\0132\022.ConversationB" +
      "adge\022\036\n\nmenuBadges\030\003 \003(\0132\n.MenuBadge\"@\n\021" +
      "ConversationBadge\022\026\n\016conversationId\030\001 \001(" +
      "\003\022\023\n\013unreadCount\030\002 \001(\005\"/\n\tMenuBadge\022\016\n\006m" +
      "enuId\030\001 \001(\t\022\022\n\nbadgeCount\030\002 \001(\005\"\226\001\n\021Call" +
      "SignalMessage\022\016\n\006callId\030\001 \001(\t\022\020\n\010callTyp" +
      "e\030\002 \001(\005\022\022\n\nsignalType\030\003 \001(\005\022\020\n\010callerId\030" +
      "\004 \001(\003\022\020\n\010calleeId\030\005 \001(\003\022\024\n\014rejectReason\030" +
      "\006 \001(\t\022\021\n\textraData\030\007 \001(\t\"\307\001\n\025WorkflowNot" +
      "ifyMessage\022\031\n\021processInstanceId\030\001 \001(\t\022\023\n" +
      "\013processName\030\002 \001(\t\022\023\n\013initiatorId\030\003 \001(\003\022" +
      "\025\n\rinitiatorName\030\004 \001(\t\022\017\n\007content\030\005 \001(\t\022" +
      " \n\007buttons\030\006 \003(\0132\017.WorkflowButton\022\016\n\006sta" +
      "tus\030\007 \001(\005\022\017\n\007jumpUrl\030\010 \001(\t\"J\n\016WorkflowBu" +
      "tton\022\020\n\010buttonId\030\001 \001(\t\022\022\n\nbuttonText\030\002 \001" +
      "(\t\022\022\n\nbuttonType\030\003 \001(\005\"\215\001\n\023TodoReminderM" +
      "essage\022\016\n\006todoId\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n" +
      "\007content\030\003 \001(\t\022\017\n\007dueTime\030\004 \001(\003\022\024\n\014remin" +
      "derType\030\005 \001(\005\022\017\n\007jumpUrl\030\006 \001(\t\022\016\n\006status" +
      "\030\007 \001(\005*\211\003\n\013MessageType\022\013\n\007UNKNOWN\020\000\022\021\n\rH" +
      "EARTBEAT_REQ\020\001\022\022\n\016HEARTBEAT_RESP\020\002\022\014\n\010AU" +
      "TH_REQ\020\003\022\r\n\tAUTH_RESP\020\004\022\t\n\005CLOSE\020\005\022\007\n\003AC" +
      "K\020\010\022\014\n\010ACK_RESP\020\t\022\010\n\004TEXT\020d\022\t\n\005IMAGE\020e\022\t" +
      "\n\005VOICE\020f\022\t\n\005VIDEO\020g\022\010\n\004FILE\020h\022\014\n\010LOCATI" +
      "ON\020i\022\n\n\006CUSTOM\020j\022\t\n\005EMOJI\020k\022\013\n\007STICKER\020l" +
      "\022\022\n\rSYSTEM_NOTIFY\020\310\001\022\021\n\014READ_RECEIPT\020\311\001\022" +
      "\013\n\006RECALL\020\312\001\022\013\n\006TYPING\020\313\001\022\021\n\014BADGE_UPDAT" +
      "E\020\314\001\022\020\n\013QUOTE_REPLY\020\315\001\022\020\n\013CALL_SIGNAL\020\316\001" +
      "\022\024\n\017WORKFLOW_NOTIFY\020\317\001\022\022\n\rTODO_REMINDER\020" +
      "\320\001BA\n-com.shengyu.framework.websocket.co" +
      "re.protocolB\016ImMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessage_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_MessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageHeader_descriptor,
        new java.lang.String[] { "MessageId", "MessageType", "SenderId", "ReceiverId", "GroupId", "TenantId", "Timestamp", "Sequence", "Extra", });
    internal_static_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthRequest_descriptor,
        new java.lang.String[] { "AccessToken", "DeviceType", "DeviceId", "ClientVersion", "Locale", });
    internal_static_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Message", "UserId", "TenantId", });
    internal_static_AckMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AckMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckMessage_descriptor,
        new java.lang.String[] { "MessageId", "ChatId", "Sequence", "AckType", "ClientReceivedAt", "OriginalTimestamp", });
    internal_static_AckResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Message", });
    internal_static_MentionUser_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_MentionUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MentionUser_descriptor,
        new java.lang.String[] { "UserId", "Nickname", "StartIndex", "EndIndex", });
    internal_static_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextMessage_descriptor,
        new java.lang.String[] { "Content", "AtUserIds", "Mentions", });
    internal_static_ImageMessage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ImageMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageMessage_descriptor,
        new java.lang.String[] { "Url", "ThumbnailUrl", "Width", "Height", "Size", "FileName", });
    internal_static_VoiceMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_VoiceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoiceMessage_descriptor,
        new java.lang.String[] { "Url", "Duration", "Size", });
    internal_static_VideoMessage_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_VideoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoMessage_descriptor,
        new java.lang.String[] { "Url", "CoverUrl", "Duration", "Width", "Height", "Size", });
    internal_static_FileMessage_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_FileMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileMessage_descriptor,
        new java.lang.String[] { "Url", "FileName", "Size", "FileType", });
    internal_static_LocationMessage_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_LocationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationMessage_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Address", });
    internal_static_ReadReceiptMessage_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ReadReceiptMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadReceiptMessage_descriptor,
        new java.lang.String[] { "MessageIds", });
    internal_static_RecallMessage_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_RecallMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecallMessage_descriptor,
        new java.lang.String[] { "MessageId", });
    internal_static_QuoteReplyMessage_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_QuoteReplyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuoteReplyMessage_descriptor,
        new java.lang.String[] { "QuoteMessageId", "QuoteContent", "QuoteSenderId", "QuoteSenderName", "ReplyContent", "AtUserIds", "Mentions", });
    internal_static_TypingMessage_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_TypingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TypingMessage_descriptor,
        new java.lang.String[] { "TargetUserId", "GroupId", "IsTyping", });
    internal_static_BadgeUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_BadgeUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BadgeUpdateMessage_descriptor,
        new java.lang.String[] { "UnreadCount", "ConversationBadges", "MenuBadges", });
    internal_static_ConversationBadge_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ConversationBadge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConversationBadge_descriptor,
        new java.lang.String[] { "ConversationId", "UnreadCount", });
    internal_static_MenuBadge_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_MenuBadge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MenuBadge_descriptor,
        new java.lang.String[] { "MenuId", "BadgeCount", });
    internal_static_CallSignalMessage_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_CallSignalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallSignalMessage_descriptor,
        new java.lang.String[] { "CallId", "CallType", "SignalType", "CallerId", "CalleeId", "RejectReason", "ExtraData", });
    internal_static_WorkflowNotifyMessage_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_WorkflowNotifyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkflowNotifyMessage_descriptor,
        new java.lang.String[] { "ProcessInstanceId", "ProcessName", "InitiatorId", "InitiatorName", "Content", "Buttons", "Status", "JumpUrl", });
    internal_static_WorkflowButton_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_WorkflowButton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkflowButton_descriptor,
        new java.lang.String[] { "ButtonId", "ButtonText", "ButtonType", });
    internal_static_TodoReminderMessage_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_TodoReminderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TodoReminderMessage_descriptor,
        new java.lang.String[] { "TodoId", "Title", "Content", "DueTime", "ReminderType", "JumpUrl", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
