// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface LocationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 纬度
   * </pre>
   *
   * <code>double latitude = 1;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <pre>
   * 经度
   * </pre>
   *
   * <code>double longitude = 2;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <pre>
   * 地址描述
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * 地址描述
   * </pre>
   *
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
