// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 菜单角标
 * </pre>
 *
 * Protobuf type {@code MenuBadge}
 */
public final class MenuBadge extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MenuBadge)
    MenuBadgeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MenuBadge.newBuilder() to construct.
  private MenuBadge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MenuBadge() {
    menuId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MenuBadge();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MenuBadge_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MenuBadge_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.MenuBadge.class, com.shengyu.framework.websocket.core.protocol.MenuBadge.Builder.class);
  }

  public static final int MENUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object menuId_;
  /**
   * <pre>
   * 菜单ID
   * </pre>
   *
   * <code>string menuId = 1;</code>
   * @return The menuId.
   */
  @java.lang.Override
  public java.lang.String getMenuId() {
    java.lang.Object ref = menuId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      menuId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 菜单ID
   * </pre>
   *
   * <code>string menuId = 1;</code>
   * @return The bytes for menuId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMenuIdBytes() {
    java.lang.Object ref = menuId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      menuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BADGECOUNT_FIELD_NUMBER = 2;
  private int badgeCount_;
  /**
   * <pre>
   * 角标数量
   * </pre>
   *
   * <code>int32 badgeCount = 2;</code>
   * @return The badgeCount.
   */
  @java.lang.Override
  public int getBadgeCount() {
    return badgeCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(menuId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, menuId_);
    }
    if (badgeCount_ != 0) {
      output.writeInt32(2, badgeCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(menuId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, menuId_);
    }
    if (badgeCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, badgeCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.MenuBadge)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.MenuBadge other = (com.shengyu.framework.websocket.core.protocol.MenuBadge) obj;

    if (!getMenuId()
        .equals(other.getMenuId())) return false;
    if (getBadgeCount()
        != other.getBadgeCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MENUID_FIELD_NUMBER;
    hash = (53 * hash) + getMenuId().hashCode();
    hash = (37 * hash) + BADGECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getBadgeCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MenuBadge parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.MenuBadge prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 菜单角标
   * </pre>
   *
   * Protobuf type {@code MenuBadge}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MenuBadge)
      com.shengyu.framework.websocket.core.protocol.MenuBadgeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MenuBadge_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MenuBadge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.MenuBadge.class, com.shengyu.framework.websocket.core.protocol.MenuBadge.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.MenuBadge.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      menuId_ = "";

      badgeCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MenuBadge_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MenuBadge getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.MenuBadge.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MenuBadge build() {
      com.shengyu.framework.websocket.core.protocol.MenuBadge result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MenuBadge buildPartial() {
      com.shengyu.framework.websocket.core.protocol.MenuBadge result = new com.shengyu.framework.websocket.core.protocol.MenuBadge(this);
      result.menuId_ = menuId_;
      result.badgeCount_ = badgeCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.MenuBadge) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.MenuBadge)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.MenuBadge other) {
      if (other == com.shengyu.framework.websocket.core.protocol.MenuBadge.getDefaultInstance()) return this;
      if (!other.getMenuId().isEmpty()) {
        menuId_ = other.menuId_;
        onChanged();
      }
      if (other.getBadgeCount() != 0) {
        setBadgeCount(other.getBadgeCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              menuId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              badgeCount_ = input.readInt32();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object menuId_ = "";
    /**
     * <pre>
     * 菜单ID
     * </pre>
     *
     * <code>string menuId = 1;</code>
     * @return The menuId.
     */
    public java.lang.String getMenuId() {
      java.lang.Object ref = menuId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        menuId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 菜单ID
     * </pre>
     *
     * <code>string menuId = 1;</code>
     * @return The bytes for menuId.
     */
    public com.google.protobuf.ByteString
        getMenuIdBytes() {
      java.lang.Object ref = menuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        menuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 菜单ID
     * </pre>
     *
     * <code>string menuId = 1;</code>
     * @param value The menuId to set.
     * @return This builder for chaining.
     */
    public Builder setMenuId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      menuId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单ID
     * </pre>
     *
     * <code>string menuId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMenuId() {
      
      menuId_ = getDefaultInstance().getMenuId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单ID
     * </pre>
     *
     * <code>string menuId = 1;</code>
     * @param value The bytes for menuId to set.
     * @return This builder for chaining.
     */
    public Builder setMenuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      menuId_ = value;
      onChanged();
      return this;
    }

    private int badgeCount_ ;
    /**
     * <pre>
     * 角标数量
     * </pre>
     *
     * <code>int32 badgeCount = 2;</code>
     * @return The badgeCount.
     */
    @java.lang.Override
    public int getBadgeCount() {
      return badgeCount_;
    }
    /**
     * <pre>
     * 角标数量
     * </pre>
     *
     * <code>int32 badgeCount = 2;</code>
     * @param value The badgeCount to set.
     * @return This builder for chaining.
     */
    public Builder setBadgeCount(int value) {
      
      badgeCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 角标数量
     * </pre>
     *
     * <code>int32 badgeCount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBadgeCount() {
      
      badgeCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MenuBadge)
  }

  // @@protoc_insertion_point(class_scope:MenuBadge)
  private static final com.shengyu.framework.websocket.core.protocol.MenuBadge DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.MenuBadge();
  }

  public static com.shengyu.framework.websocket.core.protocol.MenuBadge getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuBadge>
      PARSER = new com.google.protobuf.AbstractParser<MenuBadge>() {
    @java.lang.Override
    public MenuBadge parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MenuBadge> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuBadge> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.MenuBadge getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

