// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 消息头
 * </pre>
 *
 * Protobuf type {@code MessageHeader}
 */
public final class MessageHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MessageHeader)
    MessageHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageHeader.newBuilder() to construct.
  private MessageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageHeader() {
    messageType_ = 0;
    extra_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MessageHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MessageHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.MessageHeader.class, com.shengyu.framework.websocket.core.protocol.MessageHeader.Builder.class);
  }

  public static final int MESSAGEID_FIELD_NUMBER = 1;
  private long messageId_;
  /**
   * <pre>
   * 消息ID（雪花算法生成）
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 2;
  private int messageType_;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.MessageType messageType = 2;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.MessageType messageType = 2;</code>
   * @return The messageType.
   */
  @java.lang.Override public com.shengyu.framework.websocket.core.protocol.MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    com.shengyu.framework.websocket.core.protocol.MessageType result = com.shengyu.framework.websocket.core.protocol.MessageType.valueOf(messageType_);
    return result == null ? com.shengyu.framework.websocket.core.protocol.MessageType.UNRECOGNIZED : result;
  }

  public static final int SENDERID_FIELD_NUMBER = 3;
  private long senderId_;
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>int64 senderId = 3;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public long getSenderId() {
    return senderId_;
  }

  public static final int RECEIVERID_FIELD_NUMBER = 4;
  private long receiverId_;
  /**
   * <pre>
   * 接收者ID（单聊时使用）
   * </pre>
   *
   * <code>int64 receiverId = 4;</code>
   * @return The receiverId.
   */
  @java.lang.Override
  public long getReceiverId() {
    return receiverId_;
  }

  public static final int GROUPID_FIELD_NUMBER = 5;
  private long groupId_;
  /**
   * <pre>
   * 群组ID（群聊时使用）
   * </pre>
   *
   * <code>int64 groupId = 5;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int TENANTID_FIELD_NUMBER = 6;
  private long tenantId_;
  /**
   * <pre>
   * 租户ID
   * </pre>
   *
   * <code>int64 tenantId = 6;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public long getTenantId() {
    return tenantId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 8;
  private long sequence_;
  /**
   * <pre>
   * 序列号（用于消息去重和排序）
   * </pre>
   *
   * <code>int64 sequence = 8;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public long getSequence() {
    return sequence_;
  }

  public static final int EXTRA_FIELD_NUMBER = 9;
  private volatile java.lang.Object extra_;
  /**
   * <pre>
   * 扩展字段（JSON格式）
   * </pre>
   *
   * <code>string extra = 9;</code>
   * @return The extra.
   */
  @java.lang.Override
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展字段（JSON格式）
   * </pre>
   *
   * <code>string extra = 9;</code>
   * @return The bytes for extra.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageId_ != 0L) {
      output.writeInt64(1, messageId_);
    }
    if (messageType_ != com.shengyu.framework.websocket.core.protocol.MessageType.UNKNOWN.getNumber()) {
      output.writeEnum(2, messageType_);
    }
    if (senderId_ != 0L) {
      output.writeInt64(3, senderId_);
    }
    if (receiverId_ != 0L) {
      output.writeInt64(4, receiverId_);
    }
    if (groupId_ != 0L) {
      output.writeInt64(5, groupId_);
    }
    if (tenantId_ != 0L) {
      output.writeInt64(6, tenantId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (sequence_ != 0L) {
      output.writeInt64(8, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extra_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, extra_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageId_);
    }
    if (messageType_ != com.shengyu.framework.websocket.core.protocol.MessageType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, messageType_);
    }
    if (senderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, senderId_);
    }
    if (receiverId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, receiverId_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, groupId_);
    }
    if (tenantId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, tenantId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (sequence_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extra_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, extra_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.MessageHeader)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.MessageHeader other = (com.shengyu.framework.websocket.core.protocol.MessageHeader) obj;

    if (getMessageId()
        != other.getMessageId()) return false;
    if (messageType_ != other.messageType_) return false;
    if (getSenderId()
        != other.getSenderId()) return false;
    if (getReceiverId()
        != other.getReceiverId()) return false;
    if (getGroupId()
        != other.getGroupId()) return false;
    if (getTenantId()
        != other.getTenantId()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getSequence()
        != other.getSequence()) return false;
    if (!getExtra()
        .equals(other.getExtra())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    hash = (37 * hash) + SENDERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSenderId());
    hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiverId());
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTenantId());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSequence());
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.MessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.MessageHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 消息头
   * </pre>
   *
   * Protobuf type {@code MessageHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MessageHeader)
      com.shengyu.framework.websocket.core.protocol.MessageHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MessageHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.MessageHeader.class, com.shengyu.framework.websocket.core.protocol.MessageHeader.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.MessageHeader.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageId_ = 0L;

      messageType_ = 0;

      senderId_ = 0L;

      receiverId_ = 0L;

      groupId_ = 0L;

      tenantId_ = 0L;

      timestamp_ = 0L;

      sequence_ = 0L;

      extra_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_MessageHeader_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MessageHeader getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.MessageHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MessageHeader build() {
      com.shengyu.framework.websocket.core.protocol.MessageHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MessageHeader buildPartial() {
      com.shengyu.framework.websocket.core.protocol.MessageHeader result = new com.shengyu.framework.websocket.core.protocol.MessageHeader(this);
      result.messageId_ = messageId_;
      result.messageType_ = messageType_;
      result.senderId_ = senderId_;
      result.receiverId_ = receiverId_;
      result.groupId_ = groupId_;
      result.tenantId_ = tenantId_;
      result.timestamp_ = timestamp_;
      result.sequence_ = sequence_;
      result.extra_ = extra_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.MessageHeader) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.MessageHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.MessageHeader other) {
      if (other == com.shengyu.framework.websocket.core.protocol.MessageHeader.getDefaultInstance()) return this;
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (other.getSenderId() != 0L) {
        setSenderId(other.getSenderId());
      }
      if (other.getReceiverId() != 0L) {
        setReceiverId(other.getReceiverId());
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (other.getTenantId() != 0L) {
        setTenantId(other.getTenantId());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getSequence() != 0L) {
        setSequence(other.getSequence());
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageId_ = input.readInt64();

              break;
            } // case 8
            case 16: {
              messageType_ = input.readEnum();

              break;
            } // case 16
            case 24: {
              senderId_ = input.readInt64();

              break;
            } // case 24
            case 32: {
              receiverId_ = input.readInt64();

              break;
            } // case 32
            case 40: {
              groupId_ = input.readInt64();

              break;
            } // case 40
            case 48: {
              tenantId_ = input.readInt64();

              break;
            } // case 48
            case 56: {
              timestamp_ = input.readInt64();

              break;
            } // case 56
            case 64: {
              sequence_ = input.readInt64();

              break;
            } // case 64
            case 74: {
              extra_ = input.readStringRequireUtf8();

              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long messageId_ ;
    /**
     * <pre>
     * 消息ID（雪花算法生成）
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * 消息ID（雪花算法生成）
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {
      
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID（雪花算法生成）
     * </pre>
     *
     * <code>int64 messageId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private int messageType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 2;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 2;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 2;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.shengyu.framework.websocket.core.protocol.MessageType result = com.shengyu.framework.websocket.core.protocol.MessageType.valueOf(messageType_);
      return result == null ? com.shengyu.framework.websocket.core.protocol.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 2;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.shengyu.framework.websocket.core.protocol.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private long senderId_ ;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 senderId = 3;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 senderId = 3;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(long value) {
      
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 senderId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      
      senderId_ = 0L;
      onChanged();
      return this;
    }

    private long receiverId_ ;
    /**
     * <pre>
     * 接收者ID（单聊时使用）
     * </pre>
     *
     * <code>int64 receiverId = 4;</code>
     * @return The receiverId.
     */
    @java.lang.Override
    public long getReceiverId() {
      return receiverId_;
    }
    /**
     * <pre>
     * 接收者ID（单聊时使用）
     * </pre>
     *
     * <code>int64 receiverId = 4;</code>
     * @param value The receiverId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverId(long value) {
      
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收者ID（单聊时使用）
     * </pre>
     *
     * <code>int64 receiverId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverId() {
      
      receiverId_ = 0L;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <pre>
     * 群组ID（群聊时使用）
     * </pre>
     *
     * <code>int64 groupId = 5;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <pre>
     * 群组ID（群聊时使用）
     * </pre>
     *
     * <code>int64 groupId = 5;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {
      
      groupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 群组ID（群聊时使用）
     * </pre>
     *
     * <code>int64 groupId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private long tenantId_ ;
    /**
     * <pre>
     * 租户ID
     * </pre>
     *
     * <code>int64 tenantId = 6;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public long getTenantId() {
      return tenantId_;
    }
    /**
     * <pre>
     * 租户ID
     * </pre>
     *
     * <code>int64 tenantId = 6;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(long value) {
      
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 租户ID
     * </pre>
     *
     * <code>int64 tenantId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = 0L;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳（毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long sequence_ ;
    /**
     * <pre>
     * 序列号（用于消息去重和排序）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return sequence_;
    }
    /**
     * <pre>
     * 序列号（用于消息去重和排序）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(long value) {
      
      sequence_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 序列号（用于消息去重和排序）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      
      sequence_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <pre>
     * 扩展字段（JSON格式）
     * </pre>
     *
     * <code>string extra = 9;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段（JSON格式）
     * </pre>
     *
     * <code>string extra = 9;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段（JSON格式）
     * </pre>
     *
     * <code>string extra = 9;</code>
     * @param value The extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段（JSON格式）
     * </pre>
     *
     * <code>string extra = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段（JSON格式）
     * </pre>
     *
     * <code>string extra = 9;</code>
     * @param value The bytes for extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MessageHeader)
  }

  // @@protoc_insertion_point(class_scope:MessageHeader)
  private static final com.shengyu.framework.websocket.core.protocol.MessageHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.MessageHeader();
  }

  public static com.shengyu.framework.websocket.core.protocol.MessageHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageHeader>
      PARSER = new com.google.protobuf.AbstractParser<MessageHeader>() {
    @java.lang.Override
    public MessageHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.MessageHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

