// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface MessageHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息ID（雪花算法生成）
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.MessageType messageType = 2;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.MessageType messageType = 2;</code>
   * @return The messageType.
   */
  com.shengyu.framework.websocket.core.protocol.MessageType getMessageType();

  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>int64 senderId = 3;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <pre>
   * 接收者ID（单聊时使用）
   * </pre>
   *
   * <code>int64 receiverId = 4;</code>
   * @return The receiverId.
   */
  long getReceiverId();

  /**
   * <pre>
   * 群组ID（群聊时使用）
   * </pre>
   *
   * <code>int64 groupId = 5;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <pre>
   * 租户ID
   * </pre>
   *
   * <code>int64 tenantId = 6;</code>
   * @return The tenantId.
   */
  long getTenantId();

  /**
   * <pre>
   * 时间戳（毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 序列号（用于消息去重和排序）
   * </pre>
   *
   * <code>int64 sequence = 8;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <pre>
   * 扩展字段（JSON格式）
   * </pre>
   *
   * <code>string extra = 9;</code>
   * @return The extra.
   */
  java.lang.String getExtra();
  /**
   * <pre>
   * 扩展字段（JSON格式）
   * </pre>
   *
   * <code>string extra = 9;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();
}
