// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface ReadReceiptMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReadReceiptMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @return A list containing the messageIds.
   */
  java.util.List<java.lang.Long> getMessageIdsList();
  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @return The count of messageIds.
   */
  int getMessageIdsCount();
  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  long getMessageIds(int index);
}
