// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 消息已读回执
 * </pre>
 *
 * Protobuf type {@code ReadReceiptMessage}
 */
public final class ReadReceiptMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReadReceiptMessage)
    ReadReceiptMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReadReceiptMessage.newBuilder() to construct.
  private ReadReceiptMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReadReceiptMessage() {
    messageIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReadReceiptMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_ReadReceiptMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_ReadReceiptMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.class, com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.Builder.class);
  }

  public static final int MESSAGEIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList messageIds_;
  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @return A list containing the messageIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getMessageIdsList() {
    return messageIds_;
  }
  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @return The count of messageIds.
   */
  public int getMessageIdsCount() {
    return messageIds_.size();
  }
  /**
   * <pre>
   * 已读的消息ID列表
   * </pre>
   *
   * <code>repeated int64 messageIds = 1;</code>
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  public long getMessageIds(int index) {
    return messageIds_.getLong(index);
  }
  private int messageIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getMessageIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(messageIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < messageIds_.size(); i++) {
      output.writeInt64NoTag(messageIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < messageIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(messageIds_.getLong(i));
      }
      size += dataSize;
      if (!getMessageIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      messageIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage other = (com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage) obj;

    if (!getMessageIdsList()
        .equals(other.getMessageIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageIdsCount() > 0) {
      hash = (37 * hash) + MESSAGEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getMessageIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 消息已读回执
   * </pre>
   *
   * Protobuf type {@code ReadReceiptMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReadReceiptMessage)
      com.shengyu.framework.websocket.core.protocol.ReadReceiptMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_ReadReceiptMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_ReadReceiptMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.class, com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_ReadReceiptMessage_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage build() {
      com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage buildPartial() {
      com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage result = new com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        messageIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.messageIds_ = messageIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage other) {
      if (other == com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage.getDefaultInstance()) return this;
      if (!other.messageIds_.isEmpty()) {
        if (messageIds_.isEmpty()) {
          messageIds_ = other.messageIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMessageIdsIsMutable();
          messageIds_.addAll(other.messageIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureMessageIdsIsMutable();
              messageIds_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureMessageIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                messageIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList messageIds_ = emptyLongList();
    private void ensureMessageIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messageIds_ = mutableCopy(messageIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @return A list containing the messageIds.
     */
    public java.util.List<java.lang.Long>
        getMessageIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(messageIds_) : messageIds_;
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @return The count of messageIds.
     */
    public int getMessageIdsCount() {
      return messageIds_.size();
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @param index The index of the element to return.
     * @return The messageIds at the given index.
     */
    public long getMessageIds(int index) {
      return messageIds_.getLong(index);
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @param index The index to set the value at.
     * @param value The messageIds to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIds(
        int index, long value) {
      ensureMessageIdsIsMutable();
      messageIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @param value The messageIds to add.
     * @return This builder for chaining.
     */
    public Builder addMessageIds(long value) {
      ensureMessageIdsIsMutable();
      messageIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @param values The messageIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllMessageIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMessageIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, messageIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已读的消息ID列表
     * </pre>
     *
     * <code>repeated int64 messageIds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageIds() {
      messageIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReadReceiptMessage)
  }

  // @@protoc_insertion_point(class_scope:ReadReceiptMessage)
  private static final com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage();
  }

  public static com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadReceiptMessage>
      PARSER = new com.google.protobuf.AbstractParser<ReadReceiptMessage>() {
    @java.lang.Override
    public ReadReceiptMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReadReceiptMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadReceiptMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.ReadReceiptMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

