// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface RecallMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecallMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 撤回的消息ID
   * </pre>
   *
   * <code>int64 messageId = 1;</code>
   * @return The messageId.
   */
  long getMessageId();
}
