// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface TextMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @return A list containing the atUserIds.
   */
  java.util.List<java.lang.Long> getAtUserIdsList();
  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @return The count of atUserIds.
   */
  int getAtUserIdsCount();
  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @param index The index of the element to return.
   * @return The atUserIds at the given index.
   */
  long getAtUserIds(int index);
}
