// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 文本消息
 * </pre>
 *
 * Protobuf type {@code TextMessage}
 */
public final class TextMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TextMessage)
    TextMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TextMessage.newBuilder() to construct.
  private TextMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TextMessage() {
    content_ = "";
    atUserIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TextMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_TextMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_TextMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.TextMessage.class, com.shengyu.framework.websocket.core.protocol.TextMessage.Builder.class);
  }

  public static final int CONTENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object content_;
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATUSERIDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList atUserIds_;
  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @return A list containing the atUserIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getAtUserIdsList() {
    return atUserIds_;
  }
  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @return The count of atUserIds.
   */
  public int getAtUserIdsCount() {
    return atUserIds_.size();
  }
  /**
   * <pre>
   * &#64;用户列表
   * </pre>
   *
   * <code>repeated int64 atUserIds = 2;</code>
   * @param index The index of the element to return.
   * @return The atUserIds at the given index.
   */
  public long getAtUserIds(int index) {
    return atUserIds_.getLong(index);
  }
  private int atUserIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
    }
    if (getAtUserIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(atUserIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < atUserIds_.size(); i++) {
      output.writeInt64NoTag(atUserIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < atUserIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(atUserIds_.getLong(i));
      }
      size += dataSize;
      if (!getAtUserIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      atUserIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.TextMessage)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.TextMessage other = (com.shengyu.framework.websocket.core.protocol.TextMessage) obj;

    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getAtUserIdsList()
        .equals(other.getAtUserIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (getAtUserIdsCount() > 0) {
      hash = (37 * hash) + ATUSERIDS_FIELD_NUMBER;
      hash = (53 * hash) + getAtUserIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.TextMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.TextMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 文本消息
   * </pre>
   *
   * Protobuf type {@code TextMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TextMessage)
      com.shengyu.framework.websocket.core.protocol.TextMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_TextMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_TextMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.TextMessage.class, com.shengyu.framework.websocket.core.protocol.TextMessage.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.TextMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      content_ = "";

      atUserIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_TextMessage_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.TextMessage getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.TextMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.TextMessage build() {
      com.shengyu.framework.websocket.core.protocol.TextMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.TextMessage buildPartial() {
      com.shengyu.framework.websocket.core.protocol.TextMessage result = new com.shengyu.framework.websocket.core.protocol.TextMessage(this);
      int from_bitField0_ = bitField0_;
      result.content_ = content_;
      if (((bitField0_ & 0x00000001) != 0)) {
        atUserIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.atUserIds_ = atUserIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.TextMessage) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.TextMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.TextMessage other) {
      if (other == com.shengyu.framework.websocket.core.protocol.TextMessage.getDefaultInstance()) return this;
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.atUserIds_.isEmpty()) {
        if (atUserIds_.isEmpty()) {
          atUserIds_ = other.atUserIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAtUserIdsIsMutable();
          atUserIds_.addAll(other.atUserIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              content_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              long v = input.readInt64();
              ensureAtUserIdsIsMutable();
              atUserIds_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureAtUserIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                atUserIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList atUserIds_ = emptyLongList();
    private void ensureAtUserIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        atUserIds_ = mutableCopy(atUserIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @return A list containing the atUserIds.
     */
    public java.util.List<java.lang.Long>
        getAtUserIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(atUserIds_) : atUserIds_;
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @return The count of atUserIds.
     */
    public int getAtUserIdsCount() {
      return atUserIds_.size();
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @param index The index of the element to return.
     * @return The atUserIds at the given index.
     */
    public long getAtUserIds(int index) {
      return atUserIds_.getLong(index);
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @param index The index to set the value at.
     * @param value The atUserIds to set.
     * @return This builder for chaining.
     */
    public Builder setAtUserIds(
        int index, long value) {
      ensureAtUserIdsIsMutable();
      atUserIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @param value The atUserIds to add.
     * @return This builder for chaining.
     */
    public Builder addAtUserIds(long value) {
      ensureAtUserIdsIsMutable();
      atUserIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @param values The atUserIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllAtUserIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAtUserIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, atUserIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;用户列表
     * </pre>
     *
     * <code>repeated int64 atUserIds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAtUserIds() {
      atUserIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TextMessage)
  }

  // @@protoc_insertion_point(class_scope:TextMessage)
  private static final com.shengyu.framework.websocket.core.protocol.TextMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.TextMessage();
  }

  public static com.shengyu.framework.websocket.core.protocol.TextMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextMessage>
      PARSER = new com.google.protobuf.AbstractParser<TextMessage>() {
    @java.lang.Override
    public TextMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TextMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TextMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.TextMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

