// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface VoiceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoiceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 语音URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 语音URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 时长（秒）
   * </pre>
   *
   * <code>int32 duration = 2;</code>
   * @return The duration.
   */
  int getDuration();

  /**
   * <pre>
   * 文件大小（字节）
   * </pre>
   *
   * <code>int64 size = 3;</code>
   * @return The size.
   */
  long getSize();
}
