// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 流程操作按钮
 * </pre>
 *
 * Protobuf type {@code WorkflowButton}
 */
public final class WorkflowButton extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkflowButton)
    WorkflowButtonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkflowButton.newBuilder() to construct.
  private WorkflowButton(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkflowButton() {
    buttonId_ = "";
    buttonText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkflowButton();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowButton_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowButton_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.WorkflowButton.class, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder.class);
  }

  public static final int BUTTONID_FIELD_NUMBER = 1;
  private volatile java.lang.Object buttonId_;
  /**
   * <pre>
   * 按钮ID
   * </pre>
   *
   * <code>string buttonId = 1;</code>
   * @return The buttonId.
   */
  @java.lang.Override
  public java.lang.String getButtonId() {
    java.lang.Object ref = buttonId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buttonId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 按钮ID
   * </pre>
   *
   * <code>string buttonId = 1;</code>
   * @return The bytes for buttonId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getButtonIdBytes() {
    java.lang.Object ref = buttonId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buttonId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTONTEXT_FIELD_NUMBER = 2;
  private volatile java.lang.Object buttonText_;
  /**
   * <pre>
   * 按钮文本
   * </pre>
   *
   * <code>string buttonText = 2;</code>
   * @return The buttonText.
   */
  @java.lang.Override
  public java.lang.String getButtonText() {
    java.lang.Object ref = buttonText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buttonText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 按钮文本
   * </pre>
   *
   * <code>string buttonText = 2;</code>
   * @return The bytes for buttonText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getButtonTextBytes() {
    java.lang.Object ref = buttonText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buttonText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTONTYPE_FIELD_NUMBER = 3;
  private int buttonType_;
  /**
   * <pre>
   * 按钮类型（1-同意 2-拒绝 3-转交 4-查看详情）
   * </pre>
   *
   * <code>int32 buttonType = 3;</code>
   * @return The buttonType.
   */
  @java.lang.Override
  public int getButtonType() {
    return buttonType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buttonId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buttonId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buttonText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, buttonText_);
    }
    if (buttonType_ != 0) {
      output.writeInt32(3, buttonType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buttonId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buttonId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buttonText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, buttonText_);
    }
    if (buttonType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, buttonType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.WorkflowButton)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.WorkflowButton other = (com.shengyu.framework.websocket.core.protocol.WorkflowButton) obj;

    if (!getButtonId()
        .equals(other.getButtonId())) return false;
    if (!getButtonText()
        .equals(other.getButtonText())) return false;
    if (getButtonType()
        != other.getButtonType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUTTONID_FIELD_NUMBER;
    hash = (53 * hash) + getButtonId().hashCode();
    hash = (37 * hash) + BUTTONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getButtonText().hashCode();
    hash = (37 * hash) + BUTTONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getButtonType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.WorkflowButton prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 流程操作按钮
   * </pre>
   *
   * Protobuf type {@code WorkflowButton}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkflowButton)
      com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowButton_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowButton_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.WorkflowButton.class, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.WorkflowButton.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buttonId_ = "";

      buttonText_ = "";

      buttonType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowButton_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.WorkflowButton.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton build() {
      com.shengyu.framework.websocket.core.protocol.WorkflowButton result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton buildPartial() {
      com.shengyu.framework.websocket.core.protocol.WorkflowButton result = new com.shengyu.framework.websocket.core.protocol.WorkflowButton(this);
      result.buttonId_ = buttonId_;
      result.buttonText_ = buttonText_;
      result.buttonType_ = buttonType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.WorkflowButton) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.WorkflowButton)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.WorkflowButton other) {
      if (other == com.shengyu.framework.websocket.core.protocol.WorkflowButton.getDefaultInstance()) return this;
      if (!other.getButtonId().isEmpty()) {
        buttonId_ = other.buttonId_;
        onChanged();
      }
      if (!other.getButtonText().isEmpty()) {
        buttonText_ = other.buttonText_;
        onChanged();
      }
      if (other.getButtonType() != 0) {
        setButtonType(other.getButtonType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              buttonId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              buttonText_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              buttonType_ = input.readInt32();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object buttonId_ = "";
    /**
     * <pre>
     * 按钮ID
     * </pre>
     *
     * <code>string buttonId = 1;</code>
     * @return The buttonId.
     */
    public java.lang.String getButtonId() {
      java.lang.Object ref = buttonId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buttonId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 按钮ID
     * </pre>
     *
     * <code>string buttonId = 1;</code>
     * @return The bytes for buttonId.
     */
    public com.google.protobuf.ByteString
        getButtonIdBytes() {
      java.lang.Object ref = buttonId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buttonId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 按钮ID
     * </pre>
     *
     * <code>string buttonId = 1;</code>
     * @param value The buttonId to set.
     * @return This builder for chaining.
     */
    public Builder setButtonId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buttonId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮ID
     * </pre>
     *
     * <code>string buttonId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearButtonId() {
      
      buttonId_ = getDefaultInstance().getButtonId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮ID
     * </pre>
     *
     * <code>string buttonId = 1;</code>
     * @param value The bytes for buttonId to set.
     * @return This builder for chaining.
     */
    public Builder setButtonIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buttonId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object buttonText_ = "";
    /**
     * <pre>
     * 按钮文本
     * </pre>
     *
     * <code>string buttonText = 2;</code>
     * @return The buttonText.
     */
    public java.lang.String getButtonText() {
      java.lang.Object ref = buttonText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buttonText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 按钮文本
     * </pre>
     *
     * <code>string buttonText = 2;</code>
     * @return The bytes for buttonText.
     */
    public com.google.protobuf.ByteString
        getButtonTextBytes() {
      java.lang.Object ref = buttonText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buttonText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 按钮文本
     * </pre>
     *
     * <code>string buttonText = 2;</code>
     * @param value The buttonText to set.
     * @return This builder for chaining.
     */
    public Builder setButtonText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buttonText_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮文本
     * </pre>
     *
     * <code>string buttonText = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearButtonText() {
      
      buttonText_ = getDefaultInstance().getButtonText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮文本
     * </pre>
     *
     * <code>string buttonText = 2;</code>
     * @param value The bytes for buttonText to set.
     * @return This builder for chaining.
     */
    public Builder setButtonTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buttonText_ = value;
      onChanged();
      return this;
    }

    private int buttonType_ ;
    /**
     * <pre>
     * 按钮类型（1-同意 2-拒绝 3-转交 4-查看详情）
     * </pre>
     *
     * <code>int32 buttonType = 3;</code>
     * @return The buttonType.
     */
    @java.lang.Override
    public int getButtonType() {
      return buttonType_;
    }
    /**
     * <pre>
     * 按钮类型（1-同意 2-拒绝 3-转交 4-查看详情）
     * </pre>
     *
     * <code>int32 buttonType = 3;</code>
     * @param value The buttonType to set.
     * @return This builder for chaining.
     */
    public Builder setButtonType(int value) {
      
      buttonType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮类型（1-同意 2-拒绝 3-转交 4-查看详情）
     * </pre>
     *
     * <code>int32 buttonType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearButtonType() {
      
      buttonType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkflowButton)
  }

  // @@protoc_insertion_point(class_scope:WorkflowButton)
  private static final com.shengyu.framework.websocket.core.protocol.WorkflowButton DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.WorkflowButton();
  }

  public static com.shengyu.framework.websocket.core.protocol.WorkflowButton getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkflowButton>
      PARSER = new com.google.protobuf.AbstractParser<WorkflowButton>() {
    @java.lang.Override
    public WorkflowButton parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WorkflowButton> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkflowButton> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.WorkflowButton getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

