// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface WorkflowNotifyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkflowNotifyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 流程实例ID
   * </pre>
   *
   * <code>string processInstanceId = 1;</code>
   * @return The processInstanceId.
   */
  java.lang.String getProcessInstanceId();
  /**
   * <pre>
   * 流程实例ID
   * </pre>
   *
   * <code>string processInstanceId = 1;</code>
   * @return The bytes for processInstanceId.
   */
  com.google.protobuf.ByteString
      getProcessInstanceIdBytes();

  /**
   * <pre>
   * 流程名称
   * </pre>
   *
   * <code>string processName = 2;</code>
   * @return The processName.
   */
  java.lang.String getProcessName();
  /**
   * <pre>
   * 流程名称
   * </pre>
   *
   * <code>string processName = 2;</code>
   * @return The bytes for processName.
   */
  com.google.protobuf.ByteString
      getProcessNameBytes();

  /**
   * <pre>
   * 发起人ID
   * </pre>
   *
   * <code>int64 initiatorId = 3;</code>
   * @return The initiatorId.
   */
  long getInitiatorId();

  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string initiatorName = 4;</code>
   * @return The initiatorName.
   */
  java.lang.String getInitiatorName();
  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string initiatorName = 4;</code>
   * @return The bytes for initiatorName.
   */
  com.google.protobuf.ByteString
      getInitiatorNameBytes();

  /**
   * <pre>
   * 审批内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 审批内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton> 
      getButtonsList();
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  com.shengyu.framework.websocket.core.protocol.WorkflowButton getButtons(int index);
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  int getButtonsCount();
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  java.util.List<? extends com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder> 
      getButtonsOrBuilderList();
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder getButtonsOrBuilder(
      int index);

  /**
   * <pre>
   * 流程状态（1-待审批 2-已通过 3-已拒绝 4-已撤回）
   * </pre>
   *
   * <code>int32 status = 7;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   * 跳转URL
   * </pre>
   *
   * <code>string jumpUrl = 8;</code>
   * @return The jumpUrl.
   */
  java.lang.String getJumpUrl();
  /**
   * <pre>
   * 跳转URL
   * </pre>
   *
   * <code>string jumpUrl = 8;</code>
   * @return The bytes for jumpUrl.
   */
  com.google.protobuf.ByteString
      getJumpUrlBytes();
}
