// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

public interface WorkflowButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkflowButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 按钮ID
   * </pre>
   *
   * <code>string buttonId = 1;</code>
   * @return The buttonId.
   */
  java.lang.String getButtonId();
  /**
   * <pre>
   * 按钮ID
   * </pre>
   *
   * <code>string buttonId = 1;</code>
   * @return The bytes for buttonId.
   */
  com.google.protobuf.ByteString
      getButtonIdBytes();

  /**
   * <pre>
   * 按钮文本
   * </pre>
   *
   * <code>string buttonText = 2;</code>
   * @return The buttonText.
   */
  java.lang.String getButtonText();
  /**
   * <pre>
   * 按钮文本
   * </pre>
   *
   * <code>string buttonText = 2;</code>
   * @return The bytes for buttonText.
   */
  com.google.protobuf.ByteString
      getButtonTextBytes();

  /**
   * <pre>
   * 按钮类型（1-同意 2-拒绝 3-转交 4-查看详情）
   * </pre>
   *
   * <code>int32 buttonType = 3;</code>
   * @return The buttonType.
   */
  int getButtonType();
}
