// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_message.proto

package com.shengyu.framework.websocket.core.protocol;

/**
 * <pre>
 * 流程通知消息
 * </pre>
 *
 * Protobuf type {@code WorkflowNotifyMessage}
 */
public final class WorkflowNotifyMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkflowNotifyMessage)
    WorkflowNotifyMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkflowNotifyMessage.newBuilder() to construct.
  private WorkflowNotifyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkflowNotifyMessage() {
    processInstanceId_ = "";
    processName_ = "";
    initiatorName_ = "";
    content_ = "";
    buttons_ = java.util.Collections.emptyList();
    jumpUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkflowNotifyMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowNotifyMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowNotifyMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.class, com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.Builder.class);
  }

  public static final int PROCESSINSTANCEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object processInstanceId_;
  /**
   * <pre>
   * 流程实例ID
   * </pre>
   *
   * <code>string processInstanceId = 1;</code>
   * @return The processInstanceId.
   */
  @java.lang.Override
  public java.lang.String getProcessInstanceId() {
    java.lang.Object ref = processInstanceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processInstanceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 流程实例ID
   * </pre>
   *
   * <code>string processInstanceId = 1;</code>
   * @return The bytes for processInstanceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessInstanceIdBytes() {
    java.lang.Object ref = processInstanceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processInstanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESSNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object processName_;
  /**
   * <pre>
   * 流程名称
   * </pre>
   *
   * <code>string processName = 2;</code>
   * @return The processName.
   */
  @java.lang.Override
  public java.lang.String getProcessName() {
    java.lang.Object ref = processName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 流程名称
   * </pre>
   *
   * <code>string processName = 2;</code>
   * @return The bytes for processName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessNameBytes() {
    java.lang.Object ref = processName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIATORID_FIELD_NUMBER = 3;
  private long initiatorId_;
  /**
   * <pre>
   * 发起人ID
   * </pre>
   *
   * <code>int64 initiatorId = 3;</code>
   * @return The initiatorId.
   */
  @java.lang.Override
  public long getInitiatorId() {
    return initiatorId_;
  }

  public static final int INITIATORNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object initiatorName_;
  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string initiatorName = 4;</code>
   * @return The initiatorName.
   */
  @java.lang.Override
  public java.lang.String getInitiatorName() {
    java.lang.Object ref = initiatorName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initiatorName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string initiatorName = 4;</code>
   * @return The bytes for initiatorName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitiatorNameBytes() {
    java.lang.Object ref = initiatorName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initiatorName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  private volatile java.lang.Object content_;
  /**
   * <pre>
   * 审批内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 审批内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTONS_FIELD_NUMBER = 6;
  private java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton> buttons_;
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton> getButtonsList() {
    return buttons_;
  }
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder> 
      getButtonsOrBuilderList() {
    return buttons_;
  }
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  @java.lang.Override
  public int getButtonsCount() {
    return buttons_.size();
  }
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.WorkflowButton getButtons(int index) {
    return buttons_.get(index);
  }
  /**
   * <pre>
   * 操作按钮列表
   * </pre>
   *
   * <code>repeated .WorkflowButton buttons = 6;</code>
   */
  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder getButtonsOrBuilder(
      int index) {
    return buttons_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_;
  /**
   * <pre>
   * 流程状态（1-待审批 2-已通过 3-已拒绝 4-已撤回）
   * </pre>
   *
   * <code>int32 status = 7;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int JUMPURL_FIELD_NUMBER = 8;
  private volatile java.lang.Object jumpUrl_;
  /**
   * <pre>
   * 跳转URL
   * </pre>
   *
   * <code>string jumpUrl = 8;</code>
   * @return The jumpUrl.
   */
  @java.lang.Override
  public java.lang.String getJumpUrl() {
    java.lang.Object ref = jumpUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jumpUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 跳转URL
   * </pre>
   *
   * <code>string jumpUrl = 8;</code>
   * @return The bytes for jumpUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJumpUrlBytes() {
    java.lang.Object ref = jumpUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jumpUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processInstanceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, processInstanceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processName_);
    }
    if (initiatorId_ != 0L) {
      output.writeInt64(3, initiatorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, initiatorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
    }
    for (int i = 0; i < buttons_.size(); i++) {
      output.writeMessage(6, buttons_.get(i));
    }
    if (status_ != 0) {
      output.writeInt32(7, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jumpUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, jumpUrl_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processInstanceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, processInstanceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processName_);
    }
    if (initiatorId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, initiatorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, initiatorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
    }
    for (int i = 0; i < buttons_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, buttons_.get(i));
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jumpUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, jumpUrl_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage)) {
      return super.equals(obj);
    }
    com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage other = (com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage) obj;

    if (!getProcessInstanceId()
        .equals(other.getProcessInstanceId())) return false;
    if (!getProcessName()
        .equals(other.getProcessName())) return false;
    if (getInitiatorId()
        != other.getInitiatorId()) return false;
    if (!getInitiatorName()
        .equals(other.getInitiatorName())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getButtonsList()
        .equals(other.getButtonsList())) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (!getJumpUrl()
        .equals(other.getJumpUrl())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROCESSINSTANCEID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessInstanceId().hashCode();
    hash = (37 * hash) + PROCESSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProcessName().hashCode();
    hash = (37 * hash) + INITIATORID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInitiatorId());
    hash = (37 * hash) + INITIATORNAME_FIELD_NUMBER;
    hash = (53 * hash) + getInitiatorName().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (getButtonsCount() > 0) {
      hash = (37 * hash) + BUTTONS_FIELD_NUMBER;
      hash = (53 * hash) + getButtonsList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + JUMPURL_FIELD_NUMBER;
    hash = (53 * hash) + getJumpUrl().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 流程通知消息
   * </pre>
   *
   * Protobuf type {@code WorkflowNotifyMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkflowNotifyMessage)
      com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowNotifyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowNotifyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.class, com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.Builder.class);
    }

    // Construct using com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      processInstanceId_ = "";

      processName_ = "";

      initiatorId_ = 0L;

      initiatorName_ = "";

      content_ = "";

      if (buttonsBuilder_ == null) {
        buttons_ = java.util.Collections.emptyList();
      } else {
        buttons_ = null;
        buttonsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;

      jumpUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shengyu.framework.websocket.core.protocol.ImMessageProto.internal_static_WorkflowNotifyMessage_descriptor;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage getDefaultInstanceForType() {
      return com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage build() {
      com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage buildPartial() {
      com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage result = new com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage(this);
      int from_bitField0_ = bitField0_;
      result.processInstanceId_ = processInstanceId_;
      result.processName_ = processName_;
      result.initiatorId_ = initiatorId_;
      result.initiatorName_ = initiatorName_;
      result.content_ = content_;
      if (buttonsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          buttons_ = java.util.Collections.unmodifiableList(buttons_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.buttons_ = buttons_;
      } else {
        result.buttons_ = buttonsBuilder_.build();
      }
      result.status_ = status_;
      result.jumpUrl_ = jumpUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage) {
        return mergeFrom((com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage other) {
      if (other == com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage.getDefaultInstance()) return this;
      if (!other.getProcessInstanceId().isEmpty()) {
        processInstanceId_ = other.processInstanceId_;
        onChanged();
      }
      if (!other.getProcessName().isEmpty()) {
        processName_ = other.processName_;
        onChanged();
      }
      if (other.getInitiatorId() != 0L) {
        setInitiatorId(other.getInitiatorId());
      }
      if (!other.getInitiatorName().isEmpty()) {
        initiatorName_ = other.initiatorName_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (buttonsBuilder_ == null) {
        if (!other.buttons_.isEmpty()) {
          if (buttons_.isEmpty()) {
            buttons_ = other.buttons_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureButtonsIsMutable();
            buttons_.addAll(other.buttons_);
          }
          onChanged();
        }
      } else {
        if (!other.buttons_.isEmpty()) {
          if (buttonsBuilder_.isEmpty()) {
            buttonsBuilder_.dispose();
            buttonsBuilder_ = null;
            buttons_ = other.buttons_;
            bitField0_ = (bitField0_ & ~0x00000001);
            buttonsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getButtonsFieldBuilder() : null;
          } else {
            buttonsBuilder_.addAllMessages(other.buttons_);
          }
        }
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getJumpUrl().isEmpty()) {
        jumpUrl_ = other.jumpUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              processInstanceId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              processName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              initiatorId_ = input.readInt64();

              break;
            } // case 24
            case 34: {
              initiatorName_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              content_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              com.shengyu.framework.websocket.core.protocol.WorkflowButton m =
                  input.readMessage(
                      com.shengyu.framework.websocket.core.protocol.WorkflowButton.parser(),
                      extensionRegistry);
              if (buttonsBuilder_ == null) {
                ensureButtonsIsMutable();
                buttons_.add(m);
              } else {
                buttonsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              status_ = input.readInt32();

              break;
            } // case 56
            case 66: {
              jumpUrl_ = input.readStringRequireUtf8();

              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object processInstanceId_ = "";
    /**
     * <pre>
     * 流程实例ID
     * </pre>
     *
     * <code>string processInstanceId = 1;</code>
     * @return The processInstanceId.
     */
    public java.lang.String getProcessInstanceId() {
      java.lang.Object ref = processInstanceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processInstanceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 流程实例ID
     * </pre>
     *
     * <code>string processInstanceId = 1;</code>
     * @return The bytes for processInstanceId.
     */
    public com.google.protobuf.ByteString
        getProcessInstanceIdBytes() {
      java.lang.Object ref = processInstanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 流程实例ID
     * </pre>
     *
     * <code>string processInstanceId = 1;</code>
     * @param value The processInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setProcessInstanceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 流程实例ID
     * </pre>
     *
     * <code>string processInstanceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessInstanceId() {
      
      processInstanceId_ = getDefaultInstance().getProcessInstanceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 流程实例ID
     * </pre>
     *
     * <code>string processInstanceId = 1;</code>
     * @param value The bytes for processInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setProcessInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processInstanceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object processName_ = "";
    /**
     * <pre>
     * 流程名称
     * </pre>
     *
     * <code>string processName = 2;</code>
     * @return The processName.
     */
    public java.lang.String getProcessName() {
      java.lang.Object ref = processName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 流程名称
     * </pre>
     *
     * <code>string processName = 2;</code>
     * @return The bytes for processName.
     */
    public com.google.protobuf.ByteString
        getProcessNameBytes() {
      java.lang.Object ref = processName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 流程名称
     * </pre>
     *
     * <code>string processName = 2;</code>
     * @param value The processName to set.
     * @return This builder for chaining.
     */
    public Builder setProcessName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 流程名称
     * </pre>
     *
     * <code>string processName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessName() {
      
      processName_ = getDefaultInstance().getProcessName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 流程名称
     * </pre>
     *
     * <code>string processName = 2;</code>
     * @param value The bytes for processName to set.
     * @return This builder for chaining.
     */
    public Builder setProcessNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processName_ = value;
      onChanged();
      return this;
    }

    private long initiatorId_ ;
    /**
     * <pre>
     * 发起人ID
     * </pre>
     *
     * <code>int64 initiatorId = 3;</code>
     * @return The initiatorId.
     */
    @java.lang.Override
    public long getInitiatorId() {
      return initiatorId_;
    }
    /**
     * <pre>
     * 发起人ID
     * </pre>
     *
     * <code>int64 initiatorId = 3;</code>
     * @param value The initiatorId to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorId(long value) {
      
      initiatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发起人ID
     * </pre>
     *
     * <code>int64 initiatorId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiatorId() {
      
      initiatorId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object initiatorName_ = "";
    /**
     * <pre>
     * 发起人名称
     * </pre>
     *
     * <code>string initiatorName = 4;</code>
     * @return The initiatorName.
     */
    public java.lang.String getInitiatorName() {
      java.lang.Object ref = initiatorName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initiatorName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发起人名称
     * </pre>
     *
     * <code>string initiatorName = 4;</code>
     * @return The bytes for initiatorName.
     */
    public com.google.protobuf.ByteString
        getInitiatorNameBytes() {
      java.lang.Object ref = initiatorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initiatorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发起人名称
     * </pre>
     *
     * <code>string initiatorName = 4;</code>
     * @param value The initiatorName to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      initiatorName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发起人名称
     * </pre>
     *
     * <code>string initiatorName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiatorName() {
      
      initiatorName_ = getDefaultInstance().getInitiatorName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发起人名称
     * </pre>
     *
     * <code>string initiatorName = 4;</code>
     * @param value The bytes for initiatorName to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      initiatorName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 审批内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 审批内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 审批内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审批内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审批内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton> buttons_ =
      java.util.Collections.emptyList();
    private void ensureButtonsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        buttons_ = new java.util.ArrayList<com.shengyu.framework.websocket.core.protocol.WorkflowButton>(buttons_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.shengyu.framework.websocket.core.protocol.WorkflowButton, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder, com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder> buttonsBuilder_;

    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton> getButtonsList() {
      if (buttonsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(buttons_);
      } else {
        return buttonsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public int getButtonsCount() {
      if (buttonsBuilder_ == null) {
        return buttons_.size();
      } else {
        return buttonsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton getButtons(int index) {
      if (buttonsBuilder_ == null) {
        return buttons_.get(index);
      } else {
        return buttonsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder setButtons(
        int index, com.shengyu.framework.websocket.core.protocol.WorkflowButton value) {
      if (buttonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureButtonsIsMutable();
        buttons_.set(index, value);
        onChanged();
      } else {
        buttonsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder setButtons(
        int index, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder builderForValue) {
      if (buttonsBuilder_ == null) {
        ensureButtonsIsMutable();
        buttons_.set(index, builderForValue.build());
        onChanged();
      } else {
        buttonsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder addButtons(com.shengyu.framework.websocket.core.protocol.WorkflowButton value) {
      if (buttonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureButtonsIsMutable();
        buttons_.add(value);
        onChanged();
      } else {
        buttonsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder addButtons(
        int index, com.shengyu.framework.websocket.core.protocol.WorkflowButton value) {
      if (buttonsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureButtonsIsMutable();
        buttons_.add(index, value);
        onChanged();
      } else {
        buttonsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder addButtons(
        com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder builderForValue) {
      if (buttonsBuilder_ == null) {
        ensureButtonsIsMutable();
        buttons_.add(builderForValue.build());
        onChanged();
      } else {
        buttonsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder addButtons(
        int index, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder builderForValue) {
      if (buttonsBuilder_ == null) {
        ensureButtonsIsMutable();
        buttons_.add(index, builderForValue.build());
        onChanged();
      } else {
        buttonsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder addAllButtons(
        java.lang.Iterable<? extends com.shengyu.framework.websocket.core.protocol.WorkflowButton> values) {
      if (buttonsBuilder_ == null) {
        ensureButtonsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, buttons_);
        onChanged();
      } else {
        buttonsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder clearButtons() {
      if (buttonsBuilder_ == null) {
        buttons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        buttonsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public Builder removeButtons(int index) {
      if (buttonsBuilder_ == null) {
        ensureButtonsIsMutable();
        buttons_.remove(index);
        onChanged();
      } else {
        buttonsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder getButtonsBuilder(
        int index) {
      return getButtonsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder getButtonsOrBuilder(
        int index) {
      if (buttonsBuilder_ == null) {
        return buttons_.get(index);  } else {
        return buttonsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public java.util.List<? extends com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder> 
         getButtonsOrBuilderList() {
      if (buttonsBuilder_ != null) {
        return buttonsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(buttons_);
      }
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder addButtonsBuilder() {
      return getButtonsFieldBuilder().addBuilder(
          com.shengyu.framework.websocket.core.protocol.WorkflowButton.getDefaultInstance());
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder addButtonsBuilder(
        int index) {
      return getButtonsFieldBuilder().addBuilder(
          index, com.shengyu.framework.websocket.core.protocol.WorkflowButton.getDefaultInstance());
    }
    /**
     * <pre>
     * 操作按钮列表
     * </pre>
     *
     * <code>repeated .WorkflowButton buttons = 6;</code>
     */
    public java.util.List<com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder> 
         getButtonsBuilderList() {
      return getButtonsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.shengyu.framework.websocket.core.protocol.WorkflowButton, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder, com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder> 
        getButtonsFieldBuilder() {
      if (buttonsBuilder_ == null) {
        buttonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.shengyu.framework.websocket.core.protocol.WorkflowButton, com.shengyu.framework.websocket.core.protocol.WorkflowButton.Builder, com.shengyu.framework.websocket.core.protocol.WorkflowButtonOrBuilder>(
                buttons_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        buttons_ = null;
      }
      return buttonsBuilder_;
    }

    private int status_ ;
    /**
     * <pre>
     * 流程状态（1-待审批 2-已通过 3-已拒绝 4-已撤回）
     * </pre>
     *
     * <code>int32 status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     * 流程状态（1-待审批 2-已通过 3-已拒绝 4-已撤回）
     * </pre>
     *
     * <code>int32 status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 流程状态（1-待审批 2-已通过 3-已拒绝 4-已撤回）
     * </pre>
     *
     * <code>int32 status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object jumpUrl_ = "";
    /**
     * <pre>
     * 跳转URL
     * </pre>
     *
     * <code>string jumpUrl = 8;</code>
     * @return The jumpUrl.
     */
    public java.lang.String getJumpUrl() {
      java.lang.Object ref = jumpUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jumpUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 跳转URL
     * </pre>
     *
     * <code>string jumpUrl = 8;</code>
     * @return The bytes for jumpUrl.
     */
    public com.google.protobuf.ByteString
        getJumpUrlBytes() {
      java.lang.Object ref = jumpUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jumpUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 跳转URL
     * </pre>
     *
     * <code>string jumpUrl = 8;</code>
     * @param value The jumpUrl to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jumpUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转URL
     * </pre>
     *
     * <code>string jumpUrl = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearJumpUrl() {
      
      jumpUrl_ = getDefaultInstance().getJumpUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转URL
     * </pre>
     *
     * <code>string jumpUrl = 8;</code>
     * @param value The bytes for jumpUrl to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jumpUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkflowNotifyMessage)
  }

  // @@protoc_insertion_point(class_scope:WorkflowNotifyMessage)
  private static final com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage();
  }

  public static com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkflowNotifyMessage>
      PARSER = new com.google.protobuf.AbstractParser<WorkflowNotifyMessage>() {
    @java.lang.Override
    public WorkflowNotifyMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WorkflowNotifyMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkflowNotifyMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shengyu.framework.websocket.core.protocol.WorkflowNotifyMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

