<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.shengyu.boot</groupId>
        <artifactId>shengyu-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>shengyu-spring-boot-starter-flowlong</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>流程引擎</description>
    <url>https://gitee.com/jinzheyi/yubb-saas-pro</url>
    <dependencies>
        <dependency>
            <groupId>com.shengyu.boot</groupId>
            <artifactId>shengyu-common</artifactId>
        </dependency>

        <!-- jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <!-- Spring 核心 -->

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.shengyu.boot</groupId>
            <artifactId>shengyu-spring-boot-starter-biz-tenant</artifactId>
        </dependency>

    </dependencies>

</project>